// This file is auto-generated by @hey-api/openapi-ts

import type { DeleteOrganizationsOrgSlugResponse, DeleteUsersUserIdCalendarEventsMetaMetaIdResponse, DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse, DeleteUsersUserIdResponse, GetOrganizationsOrgSlugCalendarBusyResponse, GetOrganizationsOrgSlugMembersResponse, GetOrganizationsOrgSlugResponse, GetOrganizationsOrgSlugSchedulingResponse, GetOrganizationsResponse, GetUsersResponse, GetUsersUserIdCalendarBusyResponse, GetUsersUserIdCalendarEventsMetaMetaIdResponse, GetUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse, GetUsersUserIdCalendarEventsResponse, GetUsersUserIdCalendarResponse, GetUsersUserIdOauthLinksResponse, GetUsersUserIdOauthProviderLinkResponse, GetUsersUserIdOauthProviderResponse, GetUsersUserIdOauthResponse, GetUsersUserIdOrganizationsResponse, GetUsersUserIdResponse, GetUsersUserIdSchedulingResponse, PostOrganizationsResponse, PostUsersResponse, PostUsersUserIdCalendarEventsMetaResponse, PostUsersUserIdCalendarEventsProviderCalendarIdResponse, PostUsersUserIdOauthProviderResponse, PostUsersUserIdSchedulingResponse, PutOrganizationsOrgSlugResponse, PutUsersUserIdCalendarEventsMetaMetaIdResponse, PutUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse, PutUsersUserIdResponse } from './types.gen';

const organizationSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    if (data.members) {
        data.members = data.members.map((item: any) => {
            return userSchemaResponseTransformer(item);
        });
    }
    return data;
};

const userSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const getOrganizationsResponseTransformer = async (data: any): Promise<GetOrganizationsResponse> => {
    data.data = data.data.map((item: any) => {
        return organizationSchemaResponseTransformer(item);
    });
    return data;
};

export const postOrganizationsResponseTransformer = async (data: any): Promise<PostOrganizationsResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const deleteOrganizationsOrgSlugResponseTransformer = async (data: any): Promise<DeleteOrganizationsOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const getOrganizationsOrgSlugResponseTransformer = async (data: any): Promise<GetOrganizationsOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const putOrganizationsOrgSlugResponseTransformer = async (data: any): Promise<PutOrganizationsOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

const authConnectionSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const getOrganizationsOrgSlugMembersResponseTransformer = async (data: any): Promise<GetOrganizationsOrgSlugMembersResponse> => {
    data.data = data.data.map((item: any) => {
        item.createdAt = new Date(item.createdAt);
        if (item.oauthConnections) {
            item.oauthConnections = item.oauthConnections.map((item: any) => {
                return authConnectionSchemaResponseTransformer(item);
            });
        }
        if (item.organizations) {
            item.organizations = item.organizations.map((item: any) => {
                return organizationSchemaResponseTransformer(item);
            });
        }
        return item;
    });
    return data;
};

const timeRangeSchemaResponseTransformer = (data: any) => {
    data.end = new Date(data.end);
    data.start = new Date(data.start);
    return data;
};

export const getOrganizationsOrgSlugCalendarBusyResponseTransformer = async (data: any): Promise<GetOrganizationsOrgSlugCalendarBusyResponse> => {
    data.data = data.data.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    return data;
};

export const getOrganizationsOrgSlugSchedulingResponseTransformer = async (data: any): Promise<GetOrganizationsOrgSlugSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        item.end = new Date(item.end);
        item.start = new Date(item.start);
        return item;
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    return data;
};

export const getUsersResponseTransformer = async (data: any): Promise<GetUsersResponse> => {
    data.data = data.data.map((item: any) => {
        item.createdAt = new Date(item.createdAt);
        if (item.oauthConnections) {
            item.oauthConnections = item.oauthConnections.map((item: any) => {
                return authConnectionSchemaResponseTransformer(item);
            });
        }
        if (item.organizations) {
            item.organizations = item.organizations.map((item: any) => {
                return organizationSchemaResponseTransformer(item);
            });
        }
        return item;
    });
    return data;
};

export const postUsersResponseTransformer = async (data: any): Promise<PostUsersResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const deleteUsersUserIdResponseTransformer = async (data: any): Promise<DeleteUsersUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getUsersUserIdResponseTransformer = async (data: any): Promise<GetUsersUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const putUsersUserIdResponseTransformer = async (data: any): Promise<PutUsersUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getUsersUserIdOrganizationsResponseTransformer = async (data: any): Promise<GetUsersUserIdOrganizationsResponse> => {
    data.data = data.data.map((item: any) => {
        return organizationSchemaResponseTransformer(item);
    });
    return data;
};

export const getUsersUserIdCalendarResponseTransformer = async (data: any): Promise<GetUsersUserIdCalendarResponse> => {
    data.data = data.data.map((item: any) => {
        return calendarSchemaResponseTransformer(item);
    });
    return data;
};

export const getUsersUserIdCalendarBusyResponseTransformer = async (data: any): Promise<GetUsersUserIdCalendarBusyResponse> => {
    data.data = data.data.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    return data;
};

const eventSchemaResponseTransformer = (data: any) => {
    if (data.end) {
        data.end = new Date(data.end);
    }
    if (data.start) {
        data.start = new Date(data.start);
    }
    return data;
};

export const getUsersUserIdCalendarEventsResponseTransformer = async (data: any): Promise<GetUsersUserIdCalendarEventsResponse> => {
    data.data = data.data.map((item: any) => {
        return eventSchemaResponseTransformer(item);
    });
    return data;
};

export const postUsersUserIdCalendarEventsMetaResponseTransformer = async (data: any): Promise<PostUsersUserIdCalendarEventsMetaResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const deleteUsersUserIdCalendarEventsMetaMetaIdResponseTransformer = async (data: any): Promise<DeleteUsersUserIdCalendarEventsMetaMetaIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const getUsersUserIdCalendarEventsMetaMetaIdResponseTransformer = async (data: any): Promise<GetUsersUserIdCalendarEventsMetaMetaIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const putUsersUserIdCalendarEventsMetaMetaIdResponseTransformer = async (data: any): Promise<PutUsersUserIdCalendarEventsMetaMetaIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const postUsersUserIdCalendarEventsProviderCalendarIdResponseTransformer = async (data: any): Promise<PostUsersUserIdCalendarEventsProviderCalendarIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const deleteUsersUserIdCalendarEventsProviderCalendarIdEventIdResponseTransformer = async (data: any): Promise<DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const getUsersUserIdCalendarEventsProviderCalendarIdEventIdResponseTransformer = async (data: any): Promise<GetUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const putUsersUserIdCalendarEventsProviderCalendarIdEventIdResponseTransformer = async (data: any): Promise<PutUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const getUsersUserIdOauthResponseTransformer = async (data: any): Promise<GetUsersUserIdOauthResponse> => {
    data.data = data.data.map((item: any) => {
        return authConnectionSchemaResponseTransformer(item);
    });
    return data;
};

export const getUsersUserIdOauthProviderResponseTransformer = async (data: any): Promise<GetUsersUserIdOauthProviderResponse> => {
    data.data = authConnectionSchemaResponseTransformer(data.data);
    return data;
};

export const postUsersUserIdOauthProviderResponseTransformer = async (data: any): Promise<PostUsersUserIdOauthProviderResponse> => {
    data.data = authConnectionSchemaResponseTransformer(data.data);
    return data;
};

export const getUsersUserIdOauthLinksResponseTransformer = async (data: any): Promise<GetUsersUserIdOauthLinksResponse> => {
    data.data = authConnectionSchemaResponseTransformer(data.data);
    return data;
};

export const getUsersUserIdOauthProviderLinkResponseTransformer = async (data: any): Promise<GetUsersUserIdOauthProviderLinkResponse> => {
    data.data = authConnectionSchemaResponseTransformer(data.data);
    return data;
};

export const getUsersUserIdSchedulingResponseTransformer = async (data: any): Promise<GetUsersUserIdSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    return data;
};

export const postUsersUserIdSchedulingResponseTransformer = async (data: any): Promise<PostUsersUserIdSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    return data;
};
