// This file is auto-generated by @hey-api/openapi-ts

import type { DeleteV1OrganizationsOrgSlugResponse, DeleteV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse, DeleteV1UsersUserIdResponse, GetV1OrganizationsOrgSlugCalendarBusyResponse, GetV1OrganizationsOrgSlugMembersResponse, GetV1OrganizationsOrgSlugResponse, GetV1OrganizationsOrgSlugSchedulingResponse, GetV1OrganizationsResponse, GetV1UsersResponse, GetV1UsersUserIdCalendarBusyResponse, GetV1UsersUserIdCalendarEventsMetaMetaIdResponse, GetV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse, GetV1UsersUserIdCalendarEventsResponse, GetV1UsersUserIdCalendarResponse, GetV1UsersUserIdOauthProviderResponse, GetV1UsersUserIdOauthResponse, GetV1UsersUserIdOrganizationsResponse, GetV1UsersUserIdResponse, GetV1UsersUserIdSchedulingResponse, PostV1OrganizationsResponse, PostV1UsersResponse, PostV1UsersUserIdCalendarEventsMetaResponse, PostV1UsersUserIdCalendarEventsProviderCalendarIdResponse, PostV1UsersUserIdOauthProviderResponse, PostV1UsersUserIdSchedulingResponse, PutV1OrganizationsOrgSlugResponse, PutV1UsersUserIdCalendarEventsMetaMetaIdResponse, PutV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse, PutV1UsersUserIdResponse } from './types.gen';

const organizationSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    if (data.members) {
        data.members = data.members.map((item: any) => {
            return userSchemaResponseTransformer(item);
        });
    }
    return data;
};

const userSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const getV1OrganizationsResponseTransformer = async (data: any): Promise<GetV1OrganizationsResponse> => {
    data.data = data.data.map((item: any) => {
        return organizationSchemaResponseTransformer(item);
    });
    return data;
};

export const postV1OrganizationsResponseTransformer = async (data: any): Promise<PostV1OrganizationsResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const deleteV1OrganizationsOrgSlugResponseTransformer = async (data: any): Promise<DeleteV1OrganizationsOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const getV1OrganizationsOrgSlugResponseTransformer = async (data: any): Promise<GetV1OrganizationsOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const putV1OrganizationsOrgSlugResponseTransformer = async (data: any): Promise<PutV1OrganizationsOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

const authConnectionSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const getV1OrganizationsOrgSlugMembersResponseTransformer = async (data: any): Promise<GetV1OrganizationsOrgSlugMembersResponse> => {
    data.data = data.data.map((item: any) => {
        item.createdAt = new Date(item.createdAt);
        if (item.oauthConnections) {
            item.oauthConnections = item.oauthConnections.map((item: any) => {
                return authConnectionSchemaResponseTransformer(item);
            });
        }
        if (item.organizations) {
            item.organizations = item.organizations.map((item: any) => {
                return organizationSchemaResponseTransformer(item);
            });
        }
        return item;
    });
    return data;
};

const timeRangeSchemaResponseTransformer = (data: any) => {
    data.end = new Date(data.end);
    data.start = new Date(data.start);
    return data;
};

// Manual: HeyAPI couldn't generate transformer for Calendar schema
const calendarSchemaResponseTransformer = (data: any) => data;

export const getV1OrganizationsOrgSlugCalendarBusyResponseTransformer = async (data: any): Promise<GetV1OrganizationsOrgSlugCalendarBusyResponse> => {
    data.data = data.data.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1OrganizationsOrgSlugSchedulingResponseTransformer = async (data: any): Promise<GetV1OrganizationsOrgSlugSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        item.end = new Date(item.end);
        item.start = new Date(item.start);
        return item;
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    return data;
};

export const getV1UsersResponseTransformer = async (data: any): Promise<GetV1UsersResponse> => {
    data.data = data.data.map((item: any) => {
        item.createdAt = new Date(item.createdAt);
        if (item.oauthConnections) {
            item.oauthConnections = item.oauthConnections.map((item: any) => {
                return authConnectionSchemaResponseTransformer(item);
            });
        }
        if (item.organizations) {
            item.organizations = item.organizations.map((item: any) => {
                return organizationSchemaResponseTransformer(item);
            });
        }
        return item;
    });
    return data;
};

export const postV1UsersResponseTransformer = async (data: any): Promise<PostV1UsersResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const deleteV1UsersUserIdResponseTransformer = async (data: any): Promise<DeleteV1UsersUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getV1UsersUserIdResponseTransformer = async (data: any): Promise<GetV1UsersUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const putV1UsersUserIdResponseTransformer = async (data: any): Promise<PutV1UsersUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getV1UsersUserIdOrganizationsResponseTransformer = async (data: any): Promise<GetV1UsersUserIdOrganizationsResponse> => {
    data.data = data.data.map((item: any) => {
        return organizationSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1UsersUserIdCalendarResponseTransformer = async (data: any): Promise<GetV1UsersUserIdCalendarResponse> => {
    data.data = data.data.map((item: any) => {
        return calendarSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1UsersUserIdCalendarBusyResponseTransformer = async (data: any): Promise<GetV1UsersUserIdCalendarBusyResponse> => {
    data.data = data.data.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    return data;
};

const eventSchemaResponseTransformer = (data: any) => {
    if (data.end) {
        data.end = new Date(data.end);
    }
    if (data.start) {
        data.start = new Date(data.start);
    }
    return data;
};

export const getV1UsersUserIdCalendarEventsResponseTransformer = async (data: any): Promise<GetV1UsersUserIdCalendarEventsResponse> => {
    data.data = data.data.map((item: any) => {
        return eventSchemaResponseTransformer(item);
    });
    return data;
};

const metaEventSchemaResponseTransformer = (data: any) => {
    if (data.end) {
        data.end = new Date(data.end);
    }
    if (data.start) {
        data.start = new Date(data.start);
    }
    return data;
};

export const postV1UsersUserIdCalendarEventsMetaResponseTransformer = async (data: any): Promise<PostV1UsersUserIdCalendarEventsMetaResponse> => {
    data.data = metaEventSchemaResponseTransformer(data.data);
    return data;
};

export const getV1UsersUserIdCalendarEventsMetaMetaIdResponseTransformer = async (data: any): Promise<GetV1UsersUserIdCalendarEventsMetaMetaIdResponse> => {
    data.data = metaEventSchemaResponseTransformer(data.data);
    return data;
};

export const putV1UsersUserIdCalendarEventsMetaMetaIdResponseTransformer = async (data: any): Promise<PutV1UsersUserIdCalendarEventsMetaMetaIdResponse> => {
    data.data = metaEventSchemaResponseTransformer(data.data);
    return data;
};

export const postV1UsersUserIdCalendarEventsProviderCalendarIdResponseTransformer = async (data: any): Promise<PostV1UsersUserIdCalendarEventsProviderCalendarIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const deleteV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponseTransformer = async (data: any): Promise<DeleteV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const getV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponseTransformer = async (data: any): Promise<GetV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const putV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponseTransformer = async (data: any): Promise<PutV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const getV1UsersUserIdOauthResponseTransformer = async (data: any): Promise<GetV1UsersUserIdOauthResponse> => {
    data.data = data.data.map((item: any) => {
        return authConnectionSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1UsersUserIdOauthProviderResponseTransformer = async (data: any): Promise<GetV1UsersUserIdOauthProviderResponse> => {
    data.data = authConnectionSchemaResponseTransformer(data.data);
    return data;
};

export const postV1UsersUserIdOauthProviderResponseTransformer = async (data: any): Promise<PostV1UsersUserIdOauthProviderResponse> => {
    data.data = authConnectionSchemaResponseTransformer(data.data);
    return data;
};

export const getV1UsersUserIdSchedulingResponseTransformer = async (data: any): Promise<GetV1UsersUserIdSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    return data;
};

export const postV1UsersUserIdSchedulingResponseTransformer = async (data: any): Promise<PostV1UsersUserIdSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    return data;
};
