// This file is auto-generated by @hey-api/openapi-ts

import type { DeleteV1OrganizationsByOrgSlugResponse, DeleteV1UsersByUserIdResponse, GetV1OrganizationsByOrgSlugCalendarBusyResponse, GetV1OrganizationsByOrgSlugMembersResponse, GetV1OrganizationsByOrgSlugResponse, GetV1OrganizationsByOrgSlugSchedulingResponse, GetV1OrganizationsResponse, GetV1UsersByUserIdCalendarBusyResponse, GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponse, GetV1UsersByUserIdCalendarEventsMetaByMetaIdResponse, GetV1UsersByUserIdCalendarEventsResponse, GetV1UsersByUserIdCalendarResponse, GetV1UsersByUserIdOauthByProviderResponse, GetV1UsersByUserIdOauthResponse, GetV1UsersByUserIdOrganizationsResponse, GetV1UsersByUserIdResponse, GetV1UsersByUserIdSchedulingResponse, GetV1UsersResponse, PostV1OrganizationsResponse, PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdResponse, PostV1UsersByUserIdCalendarEventsMetaResponse, PostV1UsersByUserIdOauthByProviderResponse, PostV1UsersByUserIdSchedulingResponse, PostV1UsersResponse, PostV1UsersSchedulingResponse, PutV1OrganizationsByOrgSlugResponse, PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponse, PutV1UsersByUserIdCalendarEventsMetaByMetaIdResponse, PutV1UsersByUserIdResponse } from './types.gen';

const organizationSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    if (data.members) {
        data.members = data.members.map((item: any) => {
            return userSchemaResponseTransformer(item);
        });
    }
    return data;
};

const userSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

// Manual: HeyAPI couldn't generate a transformer for this schema
const calendarSchemaResponseTransformer = (data: any) => data;

// Manual: HeyAPI couldn't generate a transformer for this schema
const failedFreeBusyUserSchemaResponseTransformer = (data: any) => data;

export const getV1OrganizationsResponseTransformer = async (data: any): Promise<GetV1OrganizationsResponse> => {
    data.data = data.data.map((item: any) => {
        return organizationSchemaResponseTransformer(item);
    });
    return data;
};

export const postV1OrganizationsResponseTransformer = async (data: any): Promise<PostV1OrganizationsResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const deleteV1OrganizationsByOrgSlugResponseTransformer = async (data: any): Promise<DeleteV1OrganizationsByOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const getV1OrganizationsByOrgSlugResponseTransformer = async (data: any): Promise<GetV1OrganizationsByOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

export const putV1OrganizationsByOrgSlugResponseTransformer = async (data: any): Promise<PutV1OrganizationsByOrgSlugResponse> => {
    data.data = organizationSchemaResponseTransformer(data.data);
    return data;
};

const authConnectionSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const getV1OrganizationsByOrgSlugMembersResponseTransformer = async (data: any): Promise<GetV1OrganizationsByOrgSlugMembersResponse> => {
    data.data = data.data.map((item: any) => {
        item.createdAt = new Date(item.createdAt);
        if (item.oauthConnections) {
            item.oauthConnections = item.oauthConnections.map((item: any) => {
                return authConnectionSchemaResponseTransformer(item);
            });
        }
        if (item.organizations) {
            item.organizations = item.organizations.map((item: any) => {
                return organizationSchemaResponseTransformer(item);
            });
        }
        return item;
    });
    return data;
};

const timeRangeSchemaResponseTransformer = (data: any) => {
    data.end = new Date(data.end);
    data.start = new Date(data.start);
    return data;
};

export const getV1OrganizationsByOrgSlugCalendarBusyResponseTransformer = async (data: any): Promise<GetV1OrganizationsByOrgSlugCalendarBusyResponse> => {
    data.data = data.data.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    data.failedUsers = data.failedUsers.map((item: any) => {
        return failedFreeBusyUserSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1OrganizationsByOrgSlugSchedulingResponseTransformer = async (data: any): Promise<GetV1OrganizationsByOrgSlugSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        item.end = new Date(item.end);
        item.start = new Date(item.start);
        return item;
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    data.failedUsers = data.failedUsers.map((item: any) => {
        return failedFreeBusyUserSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1UsersResponseTransformer = async (data: any): Promise<GetV1UsersResponse> => {
    data.data = data.data.map((item: any) => {
        item.createdAt = new Date(item.createdAt);
        if (item.oauthConnections) {
            item.oauthConnections = item.oauthConnections.map((item: any) => {
                return authConnectionSchemaResponseTransformer(item);
            });
        }
        if (item.organizations) {
            item.organizations = item.organizations.map((item: any) => {
                return organizationSchemaResponseTransformer(item);
            });
        }
        return item;
    });
    return data;
};

export const postV1UsersResponseTransformer = async (data: any): Promise<PostV1UsersResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const deleteV1UsersByUserIdResponseTransformer = async (data: any): Promise<DeleteV1UsersByUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getV1UsersByUserIdResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const putV1UsersByUserIdResponseTransformer = async (data: any): Promise<PutV1UsersByUserIdResponse> => {
    data.data.createdAt = new Date(data.data.createdAt);
    if (data.data.oauthConnections) {
        data.data.oauthConnections = data.data.oauthConnections.map((item: any) => {
            return authConnectionSchemaResponseTransformer(item);
        });
    }
    if (data.data.organizations) {
        data.data.organizations = data.data.organizations.map((item: any) => {
            return organizationSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getV1UsersByUserIdOrganizationsResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdOrganizationsResponse> => {
    data.data = data.data.map((item: any) => {
        return organizationSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1UsersByUserIdCalendarResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdCalendarResponse> => {
    data.data = data.data.map((item: any) => {
        return calendarSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1UsersByUserIdCalendarBusyResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdCalendarBusyResponse> => {
    data.data = data.data.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    return data;
};

const eventSchemaResponseTransformer = (data: any) => {
    if (data.end) {
        data.end = new Date(data.end);
    }
    if (data.start) {
        data.start = new Date(data.start);
    }
    return data;
};

export const getV1UsersByUserIdCalendarEventsResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdCalendarEventsResponse> => {
    data.data = data.data.map((item: any) => {
        return eventSchemaResponseTransformer(item);
    });
    return data;
};

const metaEventSchemaResponseTransformer = (data: any) => {
    if (data.end) {
        data.end = new Date(data.end);
    }
    if (data.start) {
        data.start = new Date(data.start);
    }
    return data;
};

export const postV1UsersByUserIdCalendarEventsMetaResponseTransformer = async (data: any): Promise<PostV1UsersByUserIdCalendarEventsMetaResponse> => {
    data.data = metaEventSchemaResponseTransformer(data.data);
    return data;
};

export const getV1UsersByUserIdCalendarEventsMetaByMetaIdResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdCalendarEventsMetaByMetaIdResponse> => {
    data.data = metaEventSchemaResponseTransformer(data.data);
    return data;
};

export const putV1UsersByUserIdCalendarEventsMetaByMetaIdResponseTransformer = async (data: any): Promise<PutV1UsersByUserIdCalendarEventsMetaByMetaIdResponse> => {
    data.data = metaEventSchemaResponseTransformer(data.data);
    return data;
};

export const postV1UsersByUserIdCalendarEventsByProviderByCalendarIdResponseTransformer = async (data: any): Promise<PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const getV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const putV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponseTransformer = async (data: any): Promise<PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponse> => {
    data.data = eventSchemaResponseTransformer(data.data);
    return data;
};

export const getV1UsersByUserIdOauthResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdOauthResponse> => {
    data.data = data.data.map((item: any) => {
        return authConnectionSchemaResponseTransformer(item);
    });
    return data;
};

export const getV1UsersByUserIdOauthByProviderResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdOauthByProviderResponse> => {
    data.data = authConnectionSchemaResponseTransformer(data.data);
    return data;
};

export const postV1UsersByUserIdOauthByProviderResponseTransformer = async (data: any): Promise<PostV1UsersByUserIdOauthByProviderResponse> => {
    data.data = authConnectionSchemaResponseTransformer(data.data);
    return data;
};

export const getV1UsersByUserIdSchedulingResponseTransformer = async (data: any): Promise<GetV1UsersByUserIdSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    return data;
};

export const postV1UsersByUserIdSchedulingResponseTransformer = async (data: any): Promise<PostV1UsersByUserIdSchedulingResponse> => {
    data.data.availableSlots = data.data.availableSlots.map((item: any) => {
        return timeRangeSchemaResponseTransformer(item);
    });
    data.data.options.end = new Date(data.data.options.end);
    data.data.options.start = new Date(data.data.options.start);
    return data;
};

export const postV1UsersSchedulingResponseTransformer = async (data: any): Promise<PostV1UsersSchedulingResponse> => {
    data.data = data.data.map((item: any) => {
        item.availableSlots = item.availableSlots.map((item: any) => {
            return timeRangeSchemaResponseTransformer(item);
        });
        item.options.end = new Date(item.options.end);
        item.options.start = new Date(item.options.start);
        return item;
    });
    return data;
};
