// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.recal.dev' | (string & {});
};

/**
 * User
 */
export type User = {
    createdAt: Date;
    id: string;
};

/**
 * Organization
 */
export type Organization = {
    createdAt: Date;
    name: string | null;
    slug: string;
    members?: Array<User>;
};

/**
 * OAuth Connection
 */
export type AuthConnection = {
    alive: boolean;
    email: string | null;
    expiresAt: Date | null;
    provider: 'google' | 'microsoft';
    scope: Array<string>;
    accessToken?: unknown;
    refreshToken?: unknown;
};

/**
 * Recal Normalized Time Range
 */
export type TimeRange = {
    /**
     * End time of the time range in ISO format
     */
    end: Date;
    /**
     * Start time of the time range in ISO format
     */
    start: Date;
};

/**
 * Recal Normalized Calendar
 */
export type Calendar = {
    id: string;
    original: unknown;
    provider: 'google' | 'microsoft';
    accessRole?: 'freeBusyReader' | 'owner' | 'reader' | 'writer';
    backgroundColor?: string;
    foregroundColor?: string;
    selected?: boolean;
    subject?: string;
    /**
     * A valid IANA timezone identifier
     */
    timeZone?: string;
};

/**
 * Recal Normalized Event
 */
export type Event = {
    attendees: Array<{
        email: string;
        responseStatus: 'accepted' | 'declined' | 'needsAction' | 'tentative' | unknown;
    } | {
        email: string;
        self: true;
    }>;
    calendarId: string;
    id: string;
    original: unknown;
    description?: string;
    end?: Date;
    location?: string;
    metaId?: string;
    start?: Date;
    subject?: string;
};

/**
 * Recal Normalized Create Event
 */
export type CreateEventAcrossCalendars = {
    attendees?: Array<{
        email: string;
    }>;
    description?: string;
    end?: string;
    location?: string;
    meeting?: {
        url: string;
    } | boolean;
    metaId?: string;
    sendNotificationsFor?: Array<'google' | 'microsoft'>;
    start?: string;
    subject?: string;
};

/**
 * Recal Normalized Update Event
 */
export type UpdateEvent = {
    attendees?: Array<{
        email: string;
    }>;
    description?: string;
    end?: string;
    id?: string;
    location?: string;
    meeting?: {
        url: string;
    } | boolean;
    metaId?: string;
    sendNotifications?: boolean;
    start?: string;
    subject?: string;
};

/**
 * Recal Normalized Create Event
 */
export type CreateEvent = {
    attendees: Array<{
        email: string;
    }>;
    description?: string;
    end?: string;
    id?: string;
    location?: string;
    meeting?: {
        url: string;
    } | boolean;
    metaId?: string;
    sendNotifications?: boolean;
    start?: string;
    subject?: string;
};

export type GetOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type GetOrganizationsResponses = {
    /**
     * All organizations
     */
    200: {
        data: Array<Organization>;
    };
};

export type GetOrganizationsResponse = GetOrganizationsResponses[keyof GetOrganizationsResponses];

export type PostOrganizationsData = {
    body?: {
        name: string | null;
        slug: string;
    };
    path?: never;
    query?: never;
    url: '/organizations';
};

export type PostOrganizationsErrors = {
    /**
     * Organization with slug already exists
     */
    409: {
        data: null;
        error: string;
    };
};

export type PostOrganizationsError = PostOrganizationsErrors[keyof PostOrganizationsErrors];

export type PostOrganizationsResponses = {
    /**
     * Created organization
     */
    200: {
        data: Organization;
    };
};

export type PostOrganizationsResponse = PostOrganizationsResponses[keyof PostOrganizationsResponses];

export type DeleteOrganizationsOrgSlugData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/organizations/{orgSlug}';
};

export type DeleteOrganizationsOrgSlugErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteOrganizationsOrgSlugError = DeleteOrganizationsOrgSlugErrors[keyof DeleteOrganizationsOrgSlugErrors];

export type DeleteOrganizationsOrgSlugResponses = {
    /**
     * Deleted organization
     */
    200: {
        data: Organization;
    };
};

export type DeleteOrganizationsOrgSlugResponse = DeleteOrganizationsOrgSlugResponses[keyof DeleteOrganizationsOrgSlugResponses];

export type GetOrganizationsOrgSlugData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/organizations/{orgSlug}';
};

export type GetOrganizationsOrgSlugErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetOrganizationsOrgSlugError = GetOrganizationsOrgSlugErrors[keyof GetOrganizationsOrgSlugErrors];

export type GetOrganizationsOrgSlugResponses = {
    /**
     * Organization
     */
    200: {
        data: Organization;
    };
};

export type GetOrganizationsOrgSlugResponse = GetOrganizationsOrgSlugResponses[keyof GetOrganizationsOrgSlugResponses];

export type PutOrganizationsOrgSlugData = {
    body?: {
        name: string | null;
        slug: string;
    };
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/organizations/{orgSlug}';
};

export type PutOrganizationsOrgSlugErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PutOrganizationsOrgSlugError = PutOrganizationsOrgSlugErrors[keyof PutOrganizationsOrgSlugErrors];

export type PutOrganizationsOrgSlugResponses = {
    /**
     * Updated organization
     */
    200: {
        data: Organization;
    };
};

export type PutOrganizationsOrgSlugResponse = PutOrganizationsOrgSlugResponses[keyof PutOrganizationsOrgSlugResponses];

export type DeleteOrganizationsOrgSlugMembersData = {
    body?: {
        userIds: Array<string>;
    };
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/organizations/{orgSlug}/members';
};

export type DeleteOrganizationsOrgSlugMembersErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteOrganizationsOrgSlugMembersError = DeleteOrganizationsOrgSlugMembersErrors[keyof DeleteOrganizationsOrgSlugMembersErrors];

export type DeleteOrganizationsOrgSlugMembersResponses = {
    200: {
        data: string;
    };
};

export type DeleteOrganizationsOrgSlugMembersResponse = DeleteOrganizationsOrgSlugMembersResponses[keyof DeleteOrganizationsOrgSlugMembersResponses];

export type GetOrganizationsOrgSlugMembersData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query?: {
        include?: Array<'oauthConnections' | 'organizations'> | 'oauthConnections' | 'organizations';
    };
    url: '/organizations/{orgSlug}/members';
};

export type GetOrganizationsOrgSlugMembersErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetOrganizationsOrgSlugMembersError = GetOrganizationsOrgSlugMembersErrors[keyof GetOrganizationsOrgSlugMembersErrors];

export type GetOrganizationsOrgSlugMembersResponses = {
    /**
     * All members of an organization
     */
    200: {
        data: Array<{
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        }>;
    };
};

export type GetOrganizationsOrgSlugMembersResponse = GetOrganizationsOrgSlugMembersResponses[keyof GetOrganizationsOrgSlugMembersResponses];

export type PostOrganizationsOrgSlugMembersData = {
    body?: {
        userIds: Array<string>;
    };
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/organizations/{orgSlug}/members';
};

export type PostOrganizationsOrgSlugMembersErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostOrganizationsOrgSlugMembersError = PostOrganizationsOrgSlugMembersErrors[keyof PostOrganizationsOrgSlugMembersErrors];

export type PostOrganizationsOrgSlugMembersResponses = {
    /**
     * All users are already members of the organization
     */
    200: {
        data: string;
    };
    /**
     * n users added successfully to the organization
     */
    201: {
        data: string;
    };
};

export type PostOrganizationsOrgSlugMembersResponse = PostOrganizationsOrgSlugMembersResponses[keyof PostOrganizationsOrgSlugMembersResponses];

export type GetOrganizationsOrgSlugCalendarBusyData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query: {
        end: string;
        start: string;
        /**
         * Boolean query parameter (accepts "true" or "false")
         */
        primaryOnly?: 'false' | 'true';
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/organizations/{orgSlug}/calendar/busy';
};

export type GetOrganizationsOrgSlugCalendarBusyErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetOrganizationsOrgSlugCalendarBusyError = GetOrganizationsOrgSlugCalendarBusyErrors[keyof GetOrganizationsOrgSlugCalendarBusyErrors];

export type GetOrganizationsOrgSlugCalendarBusyResponses = {
    /**
     * Busy times of all users of an organization
     */
    200: {
        data: Array<TimeRange>;
    };
};

export type GetOrganizationsOrgSlugCalendarBusyResponse = GetOrganizationsOrgSlugCalendarBusyResponses[keyof GetOrganizationsOrgSlugCalendarBusyResponses];

export type GetOrganizationsOrgSlugSchedulingData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Padding in minutes to add before and after busy times
         */
        padding: string | unknown;
        /**
         * Duration of each slot in minutes
         */
        slotDuration: string | unknown;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        /**
         * Requested earliest time of each day (in the time zone of the request)
         */
        earliestTimeEachDay?: string;
        /**
         * Requested latest time of each day (in the time zone of the request)
         */
        latestTimeEachDay?: string;
        /**
         * An integer >= 0 (default: 0)
         */
        maxOverlaps?: string | unknown;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/organizations/{orgSlug}/scheduling';
};

export type GetOrganizationsOrgSlugSchedulingErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetOrganizationsOrgSlugSchedulingError = GetOrganizationsOrgSlugSchedulingErrors[keyof GetOrganizationsOrgSlugSchedulingErrors];

export type GetOrganizationsOrgSlugSchedulingResponses = {
    /**
     * Available time slots
     */
    200: {
        data: {
            availableSlots: Array<{
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                userId: string;
            }>;
            options: {
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                maxOverlaps: number;
                /**
                 * Padding in minutes to add before and after busy times
                 */
                padding: number;
                /**
                 * Duration of each slot in minutes
                 */
                slotDuration: number;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                /**
                 * Requested earliest time of each day (in the time zone of the request)
                 */
                earliestTimeEachDay?: string;
                /**
                 * Requested latest time of each day (in the time zone of the request)
                 */
                latestTimeEachDay?: string;
            };
        };
    };
};

export type GetOrganizationsOrgSlugSchedulingResponse = GetOrganizationsOrgSlugSchedulingResponses[keyof GetOrganizationsOrgSlugSchedulingResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * List of users
     */
    200: {
        data: Array<{
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        }>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body?: {
        id: string;
        organizationSlugs?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersErrors = {
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * User already exists
     */
    409: {
        data: null;
        error: string;
    };
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
    /**
     * Created user
     */
    201: {
        data: {
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        };
    };
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type DeleteUsersUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type DeleteUsersUserIdErrors = {
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteUsersUserIdError = DeleteUsersUserIdErrors[keyof DeleteUsersUserIdErrors];

export type DeleteUsersUserIdResponses = {
    /**
     * User
     */
    200: {
        data: {
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        };
    };
};

export type DeleteUsersUserIdResponse = DeleteUsersUserIdResponses[keyof DeleteUsersUserIdResponses];

export type GetUsersUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        include?: Array<'oauthConnections' | 'organizations'> | 'oauthConnections' | 'organizations';
    };
    url: '/users/{userId}';
};

export type GetUsersUserIdErrors = {
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdError = GetUsersUserIdErrors[keyof GetUsersUserIdErrors];

export type GetUsersUserIdResponses = {
    /**
     * User
     */
    200: {
        data: {
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        };
    };
};

export type GetUsersUserIdResponse = GetUsersUserIdResponses[keyof GetUsersUserIdResponses];

export type PutUsersUserIdData = {
    body?: {
        userId: string;
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type PutUsersUserIdErrors = {
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * User already exists
     */
    409: {
        data: null;
        error: string;
    };
};

export type PutUsersUserIdError = PutUsersUserIdErrors[keyof PutUsersUserIdErrors];

export type PutUsersUserIdResponses = {
    /**
     * User
     */
    200: {
        data: {
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        };
    };
};

export type PutUsersUserIdResponse = PutUsersUserIdResponses[keyof PutUsersUserIdResponses];

export type GetUsersUserIdOrganizationsData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/organizations';
};

export type GetUsersUserIdOrganizationsErrors = {
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdOrganizationsError = GetUsersUserIdOrganizationsErrors[keyof GetUsersUserIdOrganizationsErrors];

export type GetUsersUserIdOrganizationsResponses = {
    /**
     * List of organizations
     */
    200: {
        data: Array<Organization>;
    };
};

export type GetUsersUserIdOrganizationsResponse = GetUsersUserIdOrganizationsResponses[keyof GetUsersUserIdOrganizationsResponses];

export type GetUsersUserIdCalendarData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/{userId}/calendar';
};

export type GetUsersUserIdCalendarErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdCalendarError = GetUsersUserIdCalendarErrors[keyof GetUsersUserIdCalendarErrors];

export type GetUsersUserIdCalendarResponses = {
    /**
     * List of calendars
     */
    200: {
        data: Array<Calendar>;
    };
};

export type GetUsersUserIdCalendarResponse = GetUsersUserIdCalendarResponses[keyof GetUsersUserIdCalendarResponses];

export type GetUsersUserIdCalendarBusyData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        calendarIds?: Array<string>;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/{userId}/calendar/busy';
};

export type GetUsersUserIdCalendarBusyErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdCalendarBusyError = GetUsersUserIdCalendarBusyErrors[keyof GetUsersUserIdCalendarBusyErrors];

export type GetUsersUserIdCalendarBusyResponses = {
    /**
     * List of busy intervals
     */
    200: {
        data: Array<TimeRange>;
    };
};

export type GetUsersUserIdCalendarBusyResponse = GetUsersUserIdCalendarBusyResponses[keyof GetUsersUserIdCalendarBusyResponses];

export type GetUsersUserIdCalendarEventsData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        calendarIds?: Array<string>;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/{userId}/calendar/events';
};

export type GetUsersUserIdCalendarEventsErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdCalendarEventsError = GetUsersUserIdCalendarEventsErrors[keyof GetUsersUserIdCalendarEventsErrors];

export type GetUsersUserIdCalendarEventsResponses = {
    /**
     * List of events
     */
    200: {
        data: Array<Event>;
    };
};

export type GetUsersUserIdCalendarEventsResponse = GetUsersUserIdCalendarEventsResponses[keyof GetUsersUserIdCalendarEventsResponses];

export type PostUsersUserIdCalendarEventsMetaData = {
    body?: CreateEventAcrossCalendars;
    path: {
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/{userId}/calendar/events/meta';
};

export type PostUsersUserIdCalendarEventsMetaErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostUsersUserIdCalendarEventsMetaError = PostUsersUserIdCalendarEventsMetaErrors[keyof PostUsersUserIdCalendarEventsMetaErrors];

export type PostUsersUserIdCalendarEventsMetaResponses = {
    /**
     * Event created
     */
    200: {
        data: Event;
    };
};

export type PostUsersUserIdCalendarEventsMetaResponse = PostUsersUserIdCalendarEventsMetaResponses[keyof PostUsersUserIdCalendarEventsMetaResponses];

export type DeleteUsersUserIdCalendarEventsMetaMetaIdData = {
    body?: never;
    path: {
        metaId: string;
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/{userId}/calendar/events/meta/{metaId}';
};

export type DeleteUsersUserIdCalendarEventsMetaMetaIdErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * Event not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteUsersUserIdCalendarEventsMetaMetaIdError = DeleteUsersUserIdCalendarEventsMetaMetaIdErrors[keyof DeleteUsersUserIdCalendarEventsMetaMetaIdErrors];

export type DeleteUsersUserIdCalendarEventsMetaMetaIdResponses = {
    /**
     * Event deleted
     */
    200: {
        data: Event;
    };
};

export type DeleteUsersUserIdCalendarEventsMetaMetaIdResponse = DeleteUsersUserIdCalendarEventsMetaMetaIdResponses[keyof DeleteUsersUserIdCalendarEventsMetaMetaIdResponses];

export type GetUsersUserIdCalendarEventsMetaMetaIdData = {
    body?: never;
    path: {
        metaId: string;
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/{userId}/calendar/events/meta/{metaId}';
};

export type GetUsersUserIdCalendarEventsMetaMetaIdErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * Event not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdCalendarEventsMetaMetaIdError = GetUsersUserIdCalendarEventsMetaMetaIdErrors[keyof GetUsersUserIdCalendarEventsMetaMetaIdErrors];

export type GetUsersUserIdCalendarEventsMetaMetaIdResponses = {
    /**
     * Event
     */
    200: {
        data: Event;
    };
};

export type GetUsersUserIdCalendarEventsMetaMetaIdResponse = GetUsersUserIdCalendarEventsMetaMetaIdResponses[keyof GetUsersUserIdCalendarEventsMetaMetaIdResponses];

export type PutUsersUserIdCalendarEventsMetaMetaIdData = {
    body?: UpdateEvent;
    path: {
        metaId: string;
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/{userId}/calendar/events/meta/{metaId}';
};

export type PutUsersUserIdCalendarEventsMetaMetaIdErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * Event not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PutUsersUserIdCalendarEventsMetaMetaIdError = PutUsersUserIdCalendarEventsMetaMetaIdErrors[keyof PutUsersUserIdCalendarEventsMetaMetaIdErrors];

export type PutUsersUserIdCalendarEventsMetaMetaIdResponses = {
    /**
     * Event updated
     */
    200: {
        data: Event;
    };
};

export type PutUsersUserIdCalendarEventsMetaMetaIdResponse = PutUsersUserIdCalendarEventsMetaMetaIdResponses[keyof PutUsersUserIdCalendarEventsMetaMetaIdResponses];

export type PostUsersUserIdCalendarEventsProviderCalendarIdData = {
    body?: CreateEvent;
    path: {
        calendarId: string;
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/calendar/events/{provider}/{calendarId}';
};

export type PostUsersUserIdCalendarEventsProviderCalendarIdErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostUsersUserIdCalendarEventsProviderCalendarIdError = PostUsersUserIdCalendarEventsProviderCalendarIdErrors[keyof PostUsersUserIdCalendarEventsProviderCalendarIdErrors];

export type PostUsersUserIdCalendarEventsProviderCalendarIdResponses = {
    /**
     * Event created
     */
    200: {
        data: Event;
    };
};

export type PostUsersUserIdCalendarEventsProviderCalendarIdResponse = PostUsersUserIdCalendarEventsProviderCalendarIdResponses[keyof PostUsersUserIdCalendarEventsProviderCalendarIdResponses];

export type DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdData = {
    body?: never;
    path: {
        calendarId: string;
        eventId: string;
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/calendar/events/{provider}/{calendarId}/{eventId}';
};

export type DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdError = DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors[keyof DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors];

export type DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses = {
    /**
     * Event deleted
     */
    200: {
        data: Event;
    };
};

export type DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse = DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses[keyof DeleteUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses];

export type GetUsersUserIdCalendarEventsProviderCalendarIdEventIdData = {
    body?: never;
    path: {
        calendarId: string;
        eventId: string;
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/calendar/events/{provider}/{calendarId}/{eventId}';
};

export type GetUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdCalendarEventsProviderCalendarIdEventIdError = GetUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors[keyof GetUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors];

export type GetUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses = {
    /**
     * Event found
     */
    200: {
        data: Event;
    };
};

export type GetUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse = GetUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses[keyof GetUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses];

export type PutUsersUserIdCalendarEventsProviderCalendarIdEventIdData = {
    body?: UpdateEvent;
    path: {
        calendarId: string;
        eventId: string;
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/calendar/events/{provider}/{calendarId}/{eventId}';
};

export type PutUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PutUsersUserIdCalendarEventsProviderCalendarIdEventIdError = PutUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors[keyof PutUsersUserIdCalendarEventsProviderCalendarIdEventIdErrors];

export type PutUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses = {
    /**
     * Event updated
     */
    200: {
        data: Event;
    };
};

export type PutUsersUserIdCalendarEventsProviderCalendarIdEventIdResponse = PutUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses[keyof PutUsersUserIdCalendarEventsProviderCalendarIdEventIdResponses];

export type GetUsersUserIdOauthData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        /**
         * Show access and refresh tokens
         */
        showToken?: 'false' | 'true';
    };
    url: '/users/{userId}/oauth';
};

export type GetUsersUserIdOauthErrors = {
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdOauthError = GetUsersUserIdOauthErrors[keyof GetUsersUserIdOauthErrors];

export type GetUsersUserIdOauthResponses = {
    /**
     * All oauth connections of the user
     */
    200: {
        data: Array<AuthConnection>;
    };
};

export type GetUsersUserIdOauthResponse = GetUsersUserIdOauthResponses[keyof GetUsersUserIdOauthResponses];

export type DeleteUsersUserIdOauthProviderData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/oauth/{provider}';
};

export type DeleteUsersUserIdOauthProviderErrors = {
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteUsersUserIdOauthProviderError = DeleteUsersUserIdOauthProviderErrors[keyof DeleteUsersUserIdOauthProviderErrors];

export type DeleteUsersUserIdOauthProviderResponses = {
    /**
     * OAuth connection deleted
     */
    200: unknown;
};

export type GetUsersUserIdOauthProviderData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: {
        /**
         * Show access and refresh tokens
         */
        showToken?: 'false' | 'true';
    };
    url: '/users/{userId}/oauth/{provider}';
};

export type GetUsersUserIdOauthProviderErrors = {
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdOauthProviderError = GetUsersUserIdOauthProviderErrors[keyof GetUsersUserIdOauthProviderErrors];

export type GetUsersUserIdOauthProviderResponses = {
    /**
     * OAuth connection of the user
     */
    200: {
        data: AuthConnection;
    };
};

export type GetUsersUserIdOauthProviderResponse = GetUsersUserIdOauthProviderResponses[keyof GetUsersUserIdOauthProviderResponses];

export type PostUsersUserIdOauthProviderData = {
    body?: {
        accessToken: string;
        email: string | null;
        expiresAt: string | null;
        refreshToken: string | unknown;
        scope: Array<string>;
    };
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/oauth/{provider}';
};

export type PostUsersUserIdOauthProviderErrors = {
    /**
     * Invalid request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostUsersUserIdOauthProviderError = PostUsersUserIdOauthProviderErrors[keyof PostUsersUserIdOauthProviderErrors];

export type PostUsersUserIdOauthProviderResponses = {
    /**
     * OAuth connection created
     */
    201: {
        data: AuthConnection;
    };
};

export type PostUsersUserIdOauthProviderResponse = PostUsersUserIdOauthProviderResponses[keyof PostUsersUserIdOauthProviderResponses];

export type GetUsersUserIdOauthLinksData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query: {
        /**
         * Access type of the oauth connection
         */
        accessType: 'offline' | 'online';
        provider: 'google' | 'microsoft';
        /**
         * Scope of the oauth connection
         */
        scope: Array<string> | 'edit' | 'free-busy';
    };
    url: '/users/{userId}/oauth/links';
};

export type GetUsersUserIdOauthLinksErrors = {
    /**
     * Invalid request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdOauthLinksError = GetUsersUserIdOauthLinksErrors[keyof GetUsersUserIdOauthLinksErrors];

export type GetUsersUserIdOauthLinksResponses = {
    /**
     * Auth urls for the oauth providers
     */
    200: {
        data: AuthConnection;
    };
};

export type GetUsersUserIdOauthLinksResponse = GetUsersUserIdOauthLinksResponses[keyof GetUsersUserIdOauthLinksResponses];

export type GetUsersUserIdOauthProviderLinkData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query: {
        /**
         * Access type of the oauth connection
         */
        accessType: 'offline' | 'online';
        provider: 'google' | 'microsoft';
        /**
         * Redirect url for the oauth provider
         */
        redirectUrl: string;
        /**
         * Scope of the oauth connection
         */
        scope: Array<string> | 'edit' | 'free-busy';
    };
    url: '/users/{userId}/oauth/{provider}/link';
};

export type GetUsersUserIdOauthProviderLinkErrors = {
    /**
     * Invalid request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdOauthProviderLinkError = GetUsersUserIdOauthProviderLinkErrors[keyof GetUsersUserIdOauthProviderLinkErrors];

export type GetUsersUserIdOauthProviderLinkResponses = {
    /**
     * Auth url for the oauth provider
     */
    200: {
        data: AuthConnection;
    };
};

export type GetUsersUserIdOauthProviderLinkResponse = GetUsersUserIdOauthProviderLinkResponses[keyof GetUsersUserIdOauthProviderLinkResponses];

export type PostUsersOauthProviderVerifyData = {
    body?: {
        code: string;
        scope: Array<string>;
        state: string;
    };
    path: {
        provider: 'google' | 'microsoft';
    };
    query?: {
        redirectUrl?: string;
    };
    url: '/users/oauth/{provider}/verify';
};

export type PostUsersOauthProviderVerifyErrors = {
    /**
     * Invalid request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostUsersOauthProviderVerifyError = PostUsersOauthProviderVerifyErrors[keyof PostUsersOauthProviderVerifyErrors];

export type PostUsersOauthProviderVerifyResponses = {
    /**
     * OAuth code verified successfully
     */
    200: unknown;
};

export type GetUsersUserIdOauthProviderTokenData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query: {
        redirectUrl: string;
    };
    url: '/users/{userId}/oauth/{provider}/token';
};

export type GetUsersUserIdOauthProviderTokenErrors = {
    /**
     * Invalid request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdOauthProviderTokenError = GetUsersUserIdOauthProviderTokenErrors[keyof GetUsersUserIdOauthProviderTokenErrors];

export type GetUsersUserIdOauthProviderTokenResponses = {
    /**
     * Access token
     */
    200: {
        data: {
            accessToken: string;
        };
    };
};

export type GetUsersUserIdOauthProviderTokenResponse = GetUsersUserIdOauthProviderTokenResponses[keyof GetUsersUserIdOauthProviderTokenResponses];

export type GetUsersUserIdSchedulingData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Padding in minutes to add before and after busy times
         */
        padding: string | unknown;
        provider: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
        /**
         * Duration of each slot in minutes
         */
        slotDuration: string | unknown;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        /**
         * Requested earliest time of each day (in the time zone of the request)
         */
        earliestTimeEachDay?: string;
        /**
         * Requested latest time of each day (in the time zone of the request)
         */
        latestTimeEachDay?: string;
        /**
         * An integer >= 0 (default: 0)
         */
        maxOverlaps?: string | unknown;
    };
    url: '/users/{userId}/scheduling';
};

export type GetUsersUserIdSchedulingErrors = {
    /**
     * Bad request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetUsersUserIdSchedulingError = GetUsersUserIdSchedulingErrors[keyof GetUsersUserIdSchedulingErrors];

export type GetUsersUserIdSchedulingResponses = {
    /**
     * Available time slots
     */
    200: {
        data: {
            availableSlots: Array<TimeRange>;
            options: {
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                maxOverlaps: number;
                /**
                 * Padding in minutes to add before and after busy times
                 */
                padding: number;
                /**
                 * Duration of each slot in minutes
                 */
                slotDuration: number;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                /**
                 * Requested earliest time of each day (in the time zone of the request)
                 */
                earliestTimeEachDay?: string;
                /**
                 * Requested latest time of each day (in the time zone of the request)
                 */
                latestTimeEachDay?: string;
            };
        };
    };
};

export type GetUsersUserIdSchedulingResponse = GetUsersUserIdSchedulingResponses[keyof GetUsersUserIdSchedulingResponses];

export type PostUsersUserIdSchedulingData = {
    body?: {
        schedules: Array<{
            /**
             * The days to apply this scheduling element to
             */
            days: Array<'friday' | 'monday' | 'saturday' | 'sunday' | 'thursday' | 'tuesday' | 'wednesday'>;
            /**
             * End time
             */
            end: string;
            /**
             * Start time
             */
            start: string;
        }>;
    };
    path: {
        userId: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Padding in minutes to add before and after busy times
         */
        padding: string | unknown;
        /**
         * Duration of each slot in minutes
         */
        slotDuration: string | unknown;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        /**
         * An integer >= 0 (default: 0)
         */
        maxOverlaps?: string | unknown;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/{userId}/scheduling';
};

export type PostUsersUserIdSchedulingErrors = {
    /**
     * User has no connected calendars
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostUsersUserIdSchedulingError = PostUsersUserIdSchedulingErrors[keyof PostUsersUserIdSchedulingErrors];

export type PostUsersUserIdSchedulingResponses = {
    /**
     * Available time slots
     */
    200: {
        data: {
            availableSlots: Array<TimeRange>;
            options: {
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                maxOverlaps: number;
                /**
                 * Padding in minutes to add before and after busy times
                 */
                padding: number;
                /**
                 * Duration of each slot in minutes
                 */
                slotDuration: number;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                /**
                 * Requested earliest time of each day (in the time zone of the request)
                 */
                earliestTimeEachDay?: string;
                /**
                 * Requested latest time of each day (in the time zone of the request)
                 */
                latestTimeEachDay?: string;
            };
        };
    };
};

export type PostUsersUserIdSchedulingResponse = PostUsersUserIdSchedulingResponses[keyof PostUsersUserIdSchedulingResponses];

export type PostUsersSchedulingData = {
    body?: {
        users: Array<{
            id: string;
            calendarIds?: Array<string>;
            schedules?: Array<{
                /**
                 * The days to apply this scheduling element to
                 */
                days: Array<'friday' | 'monday' | 'saturday' | 'sunday' | 'thursday' | 'tuesday' | 'wednesday'>;
                /**
                 * End time
                 */
                end: string;
                /**
                 * Start time
                 */
                start: string;
            }>;
        }>;
    };
    path?: never;
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Padding in minutes to add before and after busy times
         */
        padding: string | unknown;
        /**
         * Duration of each slot in minutes
         */
        slotDuration: string | unknown;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        /**
         * An integer >= 0 (default: 0)
         */
        maxOverlaps?: string | unknown;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/users/scheduling';
};

export type PostUsersSchedulingResponses = {
    /**
     * Available time slots for each user
     */
    200: {
        data: {
            error: string;
            userId: string;
        } | Array<{
            availableSlots: Array<TimeRange>;
            options: {
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                maxOverlaps: number;
                /**
                 * Padding in minutes to add before and after busy times
                 */
                padding: number;
                /**
                 * Duration of each slot in minutes
                 */
                slotDuration: number;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                /**
                 * Requested earliest time of each day (in the time zone of the request)
                 */
                earliestTimeEachDay?: string;
                /**
                 * Requested latest time of each day (in the time zone of the request)
                 */
                latestTimeEachDay?: string;
            };
            userId: string;
            calendarIds?: Array<string>;
            schedules?: Array<{
                /**
                 * The days to apply this scheduling element to
                 */
                days: Array<'friday' | 'monday' | 'saturday' | 'sunday' | 'thursday' | 'tuesday' | 'wednesday'>;
                /**
                 * End time
                 */
                end: string;
                /**
                 * Start time
                 */
                start: string;
            }>;
        }>;
    };
};

export type PostUsersSchedulingResponse = PostUsersSchedulingResponses[keyof PostUsersSchedulingResponses];
