// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.recal.dev' | (string & {});
};

/**
 * User
 */
export type User = {
    createdAt: Date;
    id: string;
};

/**
 * Organization
 */
export type Organization = {
    createdAt: Date;
    name: string | null;
    slug: string;
    members?: Array<User>;
};

/**
 * OAuth Connection
 */
export type AuthConnection = {
    alive: boolean;
    email: string | null;
    expiresAt: Date | null;
    provider: 'google' | 'microsoft';
    scope: Array<string>;
    type: string;
    accessToken?: unknown;
    refreshToken?: unknown;
};

/**
 * Recal Normalized Time Range
 */
export type TimeRange = {
    /**
     * End time of the time range in ISO format
     */
    end: Date;
    /**
     * Start time of the time range in ISO format
     */
    start: Date;
};

/**
 * Why a calendar or a user could not be read. What each value means and how to resolve it: https://docs.recal.dev/core/troubleshooting
 */
export type FreeBusyFailureReason = 'accessDenied' | 'authorizationInvalid' | 'insufficientScopes' | 'invalidCalendarId' | 'mailboxUnavailable' | 'notFound' | 'providerError' | 'providerNotConfigured' | 'rateLimited' | 'tooManyCalendars';

/**
 * A calendar that could not be read
 */
export type FailedCalendar = {
    calendarId: string;
    message: string;
    provider: 'google' | 'microsoft';
    reason: FreeBusyFailureReason;
};

/**
 * A user whose busy times are missing (failedCalendars empty) or incomplete (failedCalendars names the gaps)
 */
export type FailedFreeBusyUser = {
    customId: string;
    failedCalendars: Array<FailedCalendar>;
    message: string;
    reason: FreeBusyFailureReason;
};

/**
 * Recal Normalized Calendar
 */
export type Calendar = {
    id: string;
    original: unknown;
    provider: 'google' | 'microsoft';
    accessRole?: 'freeBusyReader' | 'owner' | 'reader' | 'writer';
    backgroundColor?: string;
    foregroundColor?: string;
    primary?: boolean;
    selected?: boolean;
    subject?: string;
    /**
     * a valid IANA timezone identifier
     */
    timeZone?: string;
};

/**
 * Recal Normalized Event
 */
export type Event = {
    /**
     * Recal Normalized Attendee
     */
    attendees: Array<{
        email: string;
        original: unknown;
        self: true;
    } | {
        email: string;
        original: unknown;
        responseStatus?: 'accepted' | 'declined' | 'needsAction' | 'tentative';
    }>;
    calendarId: string;
    id: string;
    original: unknown;
    description?: string;
    end?: Date;
    location?: string;
    metaId?: string;
    start?: Date;
    subject?: string;
};

/**
 * Recal Normalized Meta Event
 */
export type MetaEvent = {
    /**
     * Recal Normalized Meta Event Attendee
     */
    attendees: Array<{
        email: string;
        originals: Array<unknown>;
        self: true;
    } | {
        email: string;
        originals: Array<unknown>;
        responseStatus?: 'accepted' | 'declined' | 'needsAction' | 'tentative';
    }>;
    originals: Array<unknown>;
    description?: string;
    end?: Date;
    location?: string;
    metaId?: string;
    start?: Date;
    subject?: string;
};

/**
 * Recal Normalized Create Meta Event
 */
export type CreateMetaEvent = {
    attendees?: Array<{
        email: string;
    }>;
    description?: string;
    end?: string;
    location?: string;
    meeting?: {
        url: string;
    } | boolean;
    metaId?: string;
    sendNotificationsFor?: Array<'google' | 'microsoft'>;
    start?: string;
    subject?: string;
};

/**
 * Recal Normalized Update Meta Event
 */
export type UpdateMetaEvent = {
    attendees?: Array<{
        email: string;
    }>;
    description?: string;
    end?: string;
    location?: string;
    meeting?: {
        url: string;
    } | boolean;
    metaId?: string;
    sendNotificationsFor?: Array<'google' | 'microsoft'>;
    start?: string;
    subject?: string;
};

/**
 * Recal Normalized Create Event
 */
export type CreateEvent = {
    attendees?: Array<{
        email: string;
    }>;
    description?: string;
    end?: string;
    id?: string;
    location?: string;
    meeting?: {
        url: string;
    } | boolean;
    metaId?: string;
    sendNotifications?: boolean;
    start?: string;
    subject?: string;
};

/**
 * Recal Normalized Update Event
 */
export type UpdateEvent = {
    attendees?: Array<{
        email: string;
    }>;
    description?: string;
    end?: string;
    id?: string;
    location?: string;
    meeting?: {
        url: string;
    } | boolean;
    metaId?: string;
    sendNotifications?: boolean;
    start?: string;
    subject?: string;
};

export type GetV1OrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organizations';
};

export type GetV1OrganizationsResponses = {
    /**
     * All organizations
     */
    200: {
        data: Array<Organization>;
    };
};

export type GetV1OrganizationsResponse = GetV1OrganizationsResponses[keyof GetV1OrganizationsResponses];

export type PostV1OrganizationsData = {
    body: {
        name: string | null;
        slug: string;
    };
    path?: never;
    query?: never;
    url: '/v1/organizations';
};

export type PostV1OrganizationsErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization with slug already exists
     */
    409: {
        data: null;
        error: string;
    };
};

export type PostV1OrganizationsError = PostV1OrganizationsErrors[keyof PostV1OrganizationsErrors];

export type PostV1OrganizationsResponses = {
    /**
     * Created organization
     */
    200: {
        data: Organization;
    };
};

export type PostV1OrganizationsResponse = PostV1OrganizationsResponses[keyof PostV1OrganizationsResponses];

export type DeleteV1OrganizationsByOrgSlugData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/v1/organizations/{orgSlug}';
};

export type DeleteV1OrganizationsByOrgSlugErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteV1OrganizationsByOrgSlugError = DeleteV1OrganizationsByOrgSlugErrors[keyof DeleteV1OrganizationsByOrgSlugErrors];

export type DeleteV1OrganizationsByOrgSlugResponses = {
    /**
     * Deleted organization
     */
    200: {
        data: Organization;
    };
};

export type DeleteV1OrganizationsByOrgSlugResponse = DeleteV1OrganizationsByOrgSlugResponses[keyof DeleteV1OrganizationsByOrgSlugResponses];

export type GetV1OrganizationsByOrgSlugData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/v1/organizations/{orgSlug}';
};

export type GetV1OrganizationsByOrgSlugErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1OrganizationsByOrgSlugError = GetV1OrganizationsByOrgSlugErrors[keyof GetV1OrganizationsByOrgSlugErrors];

export type GetV1OrganizationsByOrgSlugResponses = {
    /**
     * Organization
     */
    200: {
        data: Organization;
    };
};

export type GetV1OrganizationsByOrgSlugResponse = GetV1OrganizationsByOrgSlugResponses[keyof GetV1OrganizationsByOrgSlugResponses];

export type PutV1OrganizationsByOrgSlugData = {
    body: {
        name: string | null;
        slug: string;
    };
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/v1/organizations/{orgSlug}';
};

export type PutV1OrganizationsByOrgSlugErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PutV1OrganizationsByOrgSlugError = PutV1OrganizationsByOrgSlugErrors[keyof PutV1OrganizationsByOrgSlugErrors];

export type PutV1OrganizationsByOrgSlugResponses = {
    /**
     * Updated organization
     */
    200: {
        data: Organization;
    };
};

export type PutV1OrganizationsByOrgSlugResponse = PutV1OrganizationsByOrgSlugResponses[keyof PutV1OrganizationsByOrgSlugResponses];

export type DeleteV1OrganizationsByOrgSlugMembersData = {
    body: {
        userIds: Array<string>;
    };
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/v1/organizations/{orgSlug}/members';
};

export type DeleteV1OrganizationsByOrgSlugMembersErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteV1OrganizationsByOrgSlugMembersError = DeleteV1OrganizationsByOrgSlugMembersErrors[keyof DeleteV1OrganizationsByOrgSlugMembersErrors];

export type DeleteV1OrganizationsByOrgSlugMembersResponses = {
    200: {
        data: string;
    };
};

export type DeleteV1OrganizationsByOrgSlugMembersResponse = DeleteV1OrganizationsByOrgSlugMembersResponses[keyof DeleteV1OrganizationsByOrgSlugMembersResponses];

export type GetV1OrganizationsByOrgSlugMembersData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query?: {
        include?: Array<'oauthConnections' | 'organizations'> | 'oauthConnections' | 'organizations';
    };
    url: '/v1/organizations/{orgSlug}/members';
};

export type GetV1OrganizationsByOrgSlugMembersErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1OrganizationsByOrgSlugMembersError = GetV1OrganizationsByOrgSlugMembersErrors[keyof GetV1OrganizationsByOrgSlugMembersErrors];

export type GetV1OrganizationsByOrgSlugMembersResponses = {
    /**
     * All members of an organization
     */
    200: {
        data: Array<{
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        }>;
    };
};

export type GetV1OrganizationsByOrgSlugMembersResponse = GetV1OrganizationsByOrgSlugMembersResponses[keyof GetV1OrganizationsByOrgSlugMembersResponses];

export type PostV1OrganizationsByOrgSlugMembersData = {
    body: {
        userIds: Array<string>;
    };
    path: {
        orgSlug: string;
    };
    query?: never;
    url: '/v1/organizations/{orgSlug}/members';
};

export type PostV1OrganizationsByOrgSlugMembersErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostV1OrganizationsByOrgSlugMembersError = PostV1OrganizationsByOrgSlugMembersErrors[keyof PostV1OrganizationsByOrgSlugMembersErrors];

export type PostV1OrganizationsByOrgSlugMembersResponses = {
    /**
     * All users are already members of the organization
     */
    200: {
        data: string;
    };
    /**
     * n users added successfully to the organization
     */
    201: {
        data: string;
    };
};

export type PostV1OrganizationsByOrgSlugMembersResponse = PostV1OrganizationsByOrgSlugMembersResponses[keyof PostV1OrganizationsByOrgSlugMembersResponses];

export type GetV1OrganizationsByOrgSlugCalendarBusyData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query: {
        end: string;
        start: string;
        /**
         * Boolean query parameter (accepts "true" or "false")
         */
        primaryOnly?: 'false' | 'true';
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/organizations/{orgSlug}/calendar/busy';
};

export type GetV1OrganizationsByOrgSlugCalendarBusyErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1OrganizationsByOrgSlugCalendarBusyError = GetV1OrganizationsByOrgSlugCalendarBusyErrors[keyof GetV1OrganizationsByOrgSlugCalendarBusyErrors];

export type GetV1OrganizationsByOrgSlugCalendarBusyResponses = {
    /**
     * Busy times of all users of an organization, plus the users that could not be read
     */
    200: {
        data: Array<TimeRange>;
        failedUsers: Array<FailedFreeBusyUser>;
    };
};

export type GetV1OrganizationsByOrgSlugCalendarBusyResponse = GetV1OrganizationsByOrgSlugCalendarBusyResponses[keyof GetV1OrganizationsByOrgSlugCalendarBusyResponses];

export type GetV1OrganizationsByOrgSlugSchedulingData = {
    body?: never;
    path: {
        orgSlug: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        /**
         * Requested earliest time of each day (in the time zone of the request)
         */
        earliestTimeEachDay?: string;
        /**
         * Requested latest time of each day (in the time zone of the request)
         */
        latestTimeEachDay?: string;
        /**
         * an integer >= 0 (default: 0)
         */
        maxOverlaps?: string;
        /**
         * Padding in minutes to add before and after busy times
         */
        padding?: string;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
        /**
         * Duration of each slot in minutes
         */
        slotDuration?: string;
    };
    url: '/v1/organizations/{orgSlug}/scheduling';
};

export type GetV1OrganizationsByOrgSlugSchedulingErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found, or it has no members
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1OrganizationsByOrgSlugSchedulingError = GetV1OrganizationsByOrgSlugSchedulingErrors[keyof GetV1OrganizationsByOrgSlugSchedulingErrors];

export type GetV1OrganizationsByOrgSlugSchedulingResponses = {
    /**
     * Available time slots, plus the users that could not be read
     */
    200: {
        data: {
            availableSlots: Array<{
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                userId: string;
            }>;
            options: {
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                maxOverlaps: number;
                /**
                 * Padding in minutes to add before and after busy times
                 */
                padding: number;
                /**
                 * Duration of each slot in minutes
                 */
                slotDuration: number;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                /**
                 * Requested earliest time of each day (in the time zone of the request)
                 */
                earliestTimeEachDay?: string;
                /**
                 * Requested latest time of each day (in the time zone of the request)
                 */
                latestTimeEachDay?: string;
            };
        };
        failedUsers: Array<FailedFreeBusyUser>;
    };
};

export type GetV1OrganizationsByOrgSlugSchedulingResponse = GetV1OrganizationsByOrgSlugSchedulingResponses[keyof GetV1OrganizationsByOrgSlugSchedulingResponses];

export type GetV1UsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type GetV1UsersResponses = {
    /**
     * List of users
     */
    200: {
        data: Array<{
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        }>;
    };
};

export type GetV1UsersResponse = GetV1UsersResponses[keyof GetV1UsersResponses];

export type PostV1UsersData = {
    body: {
        id: string;
        organizationSlugs?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type PostV1UsersErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Organization not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * User already exists
     */
    409: {
        data: null;
        error: string;
    };
};

export type PostV1UsersError = PostV1UsersErrors[keyof PostV1UsersErrors];

export type PostV1UsersResponses = {
    /**
     * Created user
     */
    201: {
        data: {
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        };
    };
};

export type PostV1UsersResponse = PostV1UsersResponses[keyof PostV1UsersResponses];

export type DeleteV1UsersByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}';
};

export type DeleteV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type DeleteV1UsersByUserIdError = DeleteV1UsersByUserIdErrors[keyof DeleteV1UsersByUserIdErrors];

export type DeleteV1UsersByUserIdResponses = {
    /**
     * User
     */
    200: {
        data: {
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        };
    };
};

export type DeleteV1UsersByUserIdResponse = DeleteV1UsersByUserIdResponses[keyof DeleteV1UsersByUserIdResponses];

export type GetV1UsersByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        include?: Array<'oauthConnections' | 'organizations'> | 'oauthConnections' | 'organizations';
    };
    url: '/v1/users/{userId}';
};

export type GetV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdError = GetV1UsersByUserIdErrors[keyof GetV1UsersByUserIdErrors];

export type GetV1UsersByUserIdResponses = {
    /**
     * User
     */
    200: {
        data: {
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        };
    };
};

export type GetV1UsersByUserIdResponse = GetV1UsersByUserIdResponses[keyof GetV1UsersByUserIdResponses];

export type PutV1UsersByUserIdData = {
    body: {
        userId: string;
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}';
};

export type PutV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * User already exists
     */
    409: {
        data: null;
        error: string;
    };
};

export type PutV1UsersByUserIdError = PutV1UsersByUserIdErrors[keyof PutV1UsersByUserIdErrors];

export type PutV1UsersByUserIdResponses = {
    /**
     * User
     */
    200: {
        data: {
            createdAt: Date;
            id: string;
            oauthConnections?: Array<AuthConnection>;
            organizations?: Array<Organization>;
        };
    };
};

export type PutV1UsersByUserIdResponse = PutV1UsersByUserIdResponses[keyof PutV1UsersByUserIdResponses];

export type GetV1UsersByUserIdOrganizationsData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}/organizations';
};

export type GetV1UsersByUserIdOrganizationsErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdOrganizationsError = GetV1UsersByUserIdOrganizationsErrors[keyof GetV1UsersByUserIdOrganizationsErrors];

export type GetV1UsersByUserIdOrganizationsResponses = {
    /**
     * List of organizations
     */
    200: {
        data: Array<Organization>;
    };
};

export type GetV1UsersByUserIdOrganizationsResponse = GetV1UsersByUserIdOrganizationsResponses[keyof GetV1UsersByUserIdOrganizationsResponses];

export type GetV1UsersByUserIdCalendarData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/users/{userId}/calendar';
};

export type GetV1UsersByUserIdCalendarErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdCalendarError = GetV1UsersByUserIdCalendarErrors[keyof GetV1UsersByUserIdCalendarErrors];

export type GetV1UsersByUserIdCalendarResponses = {
    /**
     * List of calendars
     */
    200: {
        data: Array<Calendar>;
    };
};

export type GetV1UsersByUserIdCalendarResponse = GetV1UsersByUserIdCalendarResponses[keyof GetV1UsersByUserIdCalendarResponses];

export type GetV1UsersByUserIdCalendarBusyData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        calendarIds?: string | Array<string>;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/users/{userId}/calendar/busy';
};

export type GetV1UsersByUserIdCalendarBusyErrors = {
    /**
     * Bad request, more calendars requested than the limit allows, or every requested calendar id is invalid
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * Every requested calendar was denied by the provider, has no mailbox behind it, or the authorization does not cover busy times
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found, or none of the requested calendars exists
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled every requested calendar
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Every requested calendar could not be read
     */
    502: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdCalendarBusyError = GetV1UsersByUserIdCalendarBusyErrors[keyof GetV1UsersByUserIdCalendarBusyErrors];

export type GetV1UsersByUserIdCalendarBusyResponses = {
    /**
     * List of busy intervals, plus the calendars that could not be read
     */
    200: {
        data: Array<TimeRange>;
        failedCalendars: Array<FailedCalendar>;
    };
};

export type GetV1UsersByUserIdCalendarBusyResponse = GetV1UsersByUserIdCalendarBusyResponses[keyof GetV1UsersByUserIdCalendarBusyResponses];

export type GetV1UsersByUserIdCalendarEventsData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        calendarIds?: string | Array<string>;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/users/{userId}/calendar/events';
};

export type GetV1UsersByUserIdCalendarEventsErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdCalendarEventsError = GetV1UsersByUserIdCalendarEventsErrors[keyof GetV1UsersByUserIdCalendarEventsErrors];

export type GetV1UsersByUserIdCalendarEventsResponses = {
    /**
     * List of events
     */
    200: {
        data: Array<Event>;
    };
};

export type GetV1UsersByUserIdCalendarEventsResponse = GetV1UsersByUserIdCalendarEventsResponses[keyof GetV1UsersByUserIdCalendarEventsResponses];

export type PostV1UsersByUserIdCalendarEventsMetaData = {
    body: CreateMetaEvent;
    path: {
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/users/{userId}/calendar/events/meta';
};

export type PostV1UsersByUserIdCalendarEventsMetaErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The provider created the event, but it could not be read back into the Recal event shape
     */
    422: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type PostV1UsersByUserIdCalendarEventsMetaError = PostV1UsersByUserIdCalendarEventsMetaErrors[keyof PostV1UsersByUserIdCalendarEventsMetaErrors];

export type PostV1UsersByUserIdCalendarEventsMetaResponses = {
    /**
     * Meta event created
     */
    200: {
        data: MetaEvent;
    };
};

export type PostV1UsersByUserIdCalendarEventsMetaResponse = PostV1UsersByUserIdCalendarEventsMetaResponses[keyof PostV1UsersByUserIdCalendarEventsMetaResponses];

export type DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdData = {
    body?: never;
    path: {
        metaId: string;
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/users/{userId}/calendar/events/meta/{metaId}';
};

export type DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * Event not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdError = DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdErrors[keyof DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdErrors];

export type DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdResponses = {
    /**
     * Meta event deleted
     */
    200: {
        data: {
            success: true;
        };
    };
};

export type DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdResponse = DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdResponses[keyof DeleteV1UsersByUserIdCalendarEventsMetaByMetaIdResponses];

export type GetV1UsersByUserIdCalendarEventsMetaByMetaIdData = {
    body?: never;
    path: {
        metaId: string;
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/users/{userId}/calendar/events/meta/{metaId}';
};

export type GetV1UsersByUserIdCalendarEventsMetaByMetaIdErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * Event not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdCalendarEventsMetaByMetaIdError = GetV1UsersByUserIdCalendarEventsMetaByMetaIdErrors[keyof GetV1UsersByUserIdCalendarEventsMetaByMetaIdErrors];

export type GetV1UsersByUserIdCalendarEventsMetaByMetaIdResponses = {
    /**
     * Event
     */
    200: {
        data: MetaEvent;
    };
};

export type GetV1UsersByUserIdCalendarEventsMetaByMetaIdResponse = GetV1UsersByUserIdCalendarEventsMetaByMetaIdResponses[keyof GetV1UsersByUserIdCalendarEventsMetaByMetaIdResponses];

export type PutV1UsersByUserIdCalendarEventsMetaByMetaIdData = {
    body: UpdateMetaEvent;
    path: {
        metaId: string;
        userId: string;
    };
    query?: {
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/users/{userId}/calendar/events/meta/{metaId}';
};

export type PutV1UsersByUserIdCalendarEventsMetaByMetaIdErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * Event not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The provider applied the update, but the event could not be read back into the Recal event shape
     */
    422: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type PutV1UsersByUserIdCalendarEventsMetaByMetaIdError = PutV1UsersByUserIdCalendarEventsMetaByMetaIdErrors[keyof PutV1UsersByUserIdCalendarEventsMetaByMetaIdErrors];

export type PutV1UsersByUserIdCalendarEventsMetaByMetaIdResponses = {
    /**
     * Meta event updated
     */
    200: {
        data: MetaEvent;
    };
};

export type PutV1UsersByUserIdCalendarEventsMetaByMetaIdResponse = PutV1UsersByUserIdCalendarEventsMetaByMetaIdResponses[keyof PutV1UsersByUserIdCalendarEventsMetaByMetaIdResponses];

export type PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdData = {
    body: CreateEvent;
    path: {
        calendarId: string;
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}/calendar/events/{provider}/{calendarId}';
};

export type PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The `id` supplied for the new event is already taken on that calendar. Google only: the Microsoft path never forwards a caller-supplied id
     */
    409: {
        data: null;
        error: string;
    };
    /**
     * The provider created the event, but it could not be read back into the Recal event shape
     */
    422: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdError = PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdErrors[keyof PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdErrors];

export type PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdResponses = {
    /**
     * Event created
     */
    200: {
        data: Event;
    };
};

export type PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdResponse = PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdResponses[keyof PostV1UsersByUserIdCalendarEventsByProviderByCalendarIdResponses];

export type DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdData = {
    body?: never;
    path: {
        calendarId: string;
        eventId: string;
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}/calendar/events/{provider}/{calendarId}/{eventId}';
};

export type DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdError = DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors[keyof DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors];

export type DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses = {
    /**
     * Event deleted
     */
    200: {
        data: {
            success: true;
        };
    };
};

export type DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponse = DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses[keyof DeleteV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses];

export type GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdData = {
    body?: never;
    path: {
        calendarId: string;
        eventId: string;
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}/calendar/events/{provider}/{calendarId}/{eventId}';
};

export type GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdError = GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors[keyof GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors];

export type GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses = {
    /**
     * Event found
     */
    200: {
        data: Event;
    };
};

export type GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponse = GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses[keyof GetV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses];

export type PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdData = {
    body: UpdateEvent;
    path: {
        calendarId: string;
        eventId: string;
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}/calendar/events/{provider}/{calendarId}/{eventId}';
};

export type PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * The calendar authorization does not cover the operation. A scope refusal also carries `operation` alongside the envelope, plus `validScopes` when Recal's own pre-flight raised it; a flat denial from the provider carries neither
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The provider applied the update, but the event could not be read back into the Recal event shape
     */
    422: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled the request. When it says how long to wait, the response carries a `Retry-After` header and a `retryAfter` field alongside the envelope
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Calendar provider unreachable or returned an unreadable response
     */
    502: {
        data: null;
        error: string;
    };
};

export type PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdError = PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors[keyof PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdErrors];

export type PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses = {
    /**
     * Event updated
     */
    200: {
        data: Event;
    };
};

export type PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponse = PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses[keyof PutV1UsersByUserIdCalendarEventsByProviderByCalendarIdByEventIdResponses];

export type GetV1UsersByUserIdOauthData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        /**
         * Show access and refresh tokens
         */
        showToken?: 'false' | 'true';
    };
    url: '/v1/users/{userId}/oauth';
};

export type GetV1UsersByUserIdOauthErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdOauthError = GetV1UsersByUserIdOauthErrors[keyof GetV1UsersByUserIdOauthErrors];

export type GetV1UsersByUserIdOauthResponses = {
    /**
     * All oauth connections of the user
     */
    200: {
        data: Array<AuthConnection>;
    };
};

export type GetV1UsersByUserIdOauthResponse = GetV1UsersByUserIdOauthResponses[keyof GetV1UsersByUserIdOauthResponses];

export type GetV1UsersByUserIdOauthLinksData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        /**
         * Access type of the oauth connection
         */
        accessType: 'offline' | 'online';
        /**
         * Scope of the oauth connection
         */
        scope: Array<string> | 'edit' | 'free-busy' | 'read' | 'write';
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
    };
    url: '/v1/users/{userId}/oauth/links';
};

export type GetV1UsersByUserIdOauthLinksErrors = {
    /**
     * Invalid request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdOauthLinksError = GetV1UsersByUserIdOauthLinksErrors[keyof GetV1UsersByUserIdOauthLinksErrors];

export type GetV1UsersByUserIdOauthLinksResponses = {
    /**
     * Auth urls for the oauth providers
     */
    200: {
        data: Array<{
            /**
             * Auth url for the user to connect to the oauth provider
             */
            link: string;
            provider: 'google' | 'microsoft';
        }>;
    };
};

export type GetV1UsersByUserIdOauthLinksResponse = GetV1UsersByUserIdOauthLinksResponses[keyof GetV1UsersByUserIdOauthLinksResponses];

export type GetV1UsersByUserIdOauthByProviderLinkData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query: {
        /**
         * Access type of the oauth connection
         */
        accessType: 'offline' | 'online';
        /**
         * Scope of the oauth connection
         */
        scope: Array<string> | 'edit' | 'free-busy' | 'read' | 'write';
        /**
         * Redirect url for the oauth provider
         */
        redirectUrl?: string;
    };
    url: '/v1/users/{userId}/oauth/{provider}/link';
};

export type GetV1UsersByUserIdOauthByProviderLinkErrors = {
    /**
     * Invalid request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdOauthByProviderLinkError = GetV1UsersByUserIdOauthByProviderLinkErrors[keyof GetV1UsersByUserIdOauthByProviderLinkErrors];

export type GetV1UsersByUserIdOauthByProviderLinkResponses = {
    /**
     * Auth url for the oauth provider
     */
    200: {
        data: {
            /**
             * Auth url for the user to connect to the oauth provider
             */
            link: string;
        };
    };
};

export type GetV1UsersByUserIdOauthByProviderLinkResponse = GetV1UsersByUserIdOauthByProviderLinkResponses[keyof GetV1UsersByUserIdOauthByProviderLinkResponses];

export type PostV1UsersOauthByProviderVerifyData = {
    body: {
        code: string;
        scope: Array<string>;
        state: string;
    };
    path: {
        provider: 'google' | 'microsoft';
    };
    query?: {
        /**
         * Redirect url for the oauth provider
         */
        redirectUrl?: string;
    };
    url: '/v1/users/oauth/{provider}/verify';
};

export type PostV1UsersOauthByProviderVerifyErrors = {
    /**
     * Invalid request
     */
    400: {
        data: null;
        error: string;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostV1UsersOauthByProviderVerifyError = PostV1UsersOauthByProviderVerifyErrors[keyof PostV1UsersOauthByProviderVerifyErrors];

export type PostV1UsersOauthByProviderVerifyResponses = {
    /**
     * OAuth code verified successfully
     */
    200: unknown;
};

export type DeleteV1UsersByUserIdOauthByProviderData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}/oauth/{provider}';
};

export type DeleteV1UsersByUserIdOauthByProviderErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        data: null;
        error: string;
    };
};

export type DeleteV1UsersByUserIdOauthByProviderError = DeleteV1UsersByUserIdOauthByProviderErrors[keyof DeleteV1UsersByUserIdOauthByProviderErrors];

export type DeleteV1UsersByUserIdOauthByProviderResponses = {
    /**
     * OAuth connection deleted
     */
    200: unknown;
};

export type GetV1UsersByUserIdOauthByProviderData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: {
        /**
         * Show access and refresh tokens
         */
        showToken?: 'false' | 'true';
    };
    url: '/v1/users/{userId}/oauth/{provider}';
};

export type GetV1UsersByUserIdOauthByProviderErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdOauthByProviderError = GetV1UsersByUserIdOauthByProviderErrors[keyof GetV1UsersByUserIdOauthByProviderErrors];

export type GetV1UsersByUserIdOauthByProviderResponses = {
    /**
     * OAuth connection of the user
     */
    200: {
        data: AuthConnection;
    };
};

export type GetV1UsersByUserIdOauthByProviderResponse = GetV1UsersByUserIdOauthByProviderResponses[keyof GetV1UsersByUserIdOauthByProviderResponses];

export type PostV1UsersByUserIdOauthByProviderData = {
    body: {
        accessToken: string;
        email: string | null;
        expiresAt: string | null;
        refreshToken: string | unknown;
        scope: Array<string>;
    };
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}/oauth/{provider}';
};

export type PostV1UsersByUserIdOauthByProviderErrors = {
    /**
     * Invalid request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type PostV1UsersByUserIdOauthByProviderError = PostV1UsersByUserIdOauthByProviderErrors[keyof PostV1UsersByUserIdOauthByProviderErrors];

export type PostV1UsersByUserIdOauthByProviderResponses = {
    /**
     * OAuth connection created
     */
    201: {
        data: AuthConnection;
    };
};

export type PostV1UsersByUserIdOauthByProviderResponse = PostV1UsersByUserIdOauthByProviderResponses[keyof PostV1UsersByUserIdOauthByProviderResponses];

export type GetV1UsersByUserIdOauthByProviderTokenData = {
    body?: never;
    path: {
        provider: 'google' | 'microsoft';
        userId: string;
    };
    query?: never;
    url: '/v1/users/{userId}/oauth/{provider}/token';
};

export type GetV1UsersByUserIdOauthByProviderTokenErrors = {
    /**
     * Invalid request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * User not found
     */
    404: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdOauthByProviderTokenError = GetV1UsersByUserIdOauthByProviderTokenErrors[keyof GetV1UsersByUserIdOauthByProviderTokenErrors];

export type GetV1UsersByUserIdOauthByProviderTokenResponses = {
    /**
     * Access token
     */
    200: {
        data: {
            accessToken: string;
        };
    };
};

export type GetV1UsersByUserIdOauthByProviderTokenResponse = GetV1UsersByUserIdOauthByProviderTokenResponses[keyof GetV1UsersByUserIdOauthByProviderTokenResponses];

export type GetV1UsersByUserIdSchedulingData = {
    body?: never;
    path: {
        userId: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        /**
         * Requested earliest time of each day (in the time zone of the request)
         */
        earliestTimeEachDay?: string;
        /**
         * Requested latest time of each day (in the time zone of the request)
         */
        latestTimeEachDay?: string;
        /**
         * an integer >= 0 (default: 0)
         */
        maxOverlaps?: string;
        /**
         * Padding in minutes to add before and after busy times
         */
        padding?: string;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
        /**
         * Duration of each slot in minutes
         */
        slotDuration?: string;
    };
    url: '/v1/users/{userId}/scheduling';
};

export type GetV1UsersByUserIdSchedulingErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * Every requested calendar was denied by the provider, has no mailbox behind it, or the authorization does not cover busy times
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found, or the user has no connected calendars
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled every requested calendar
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Every requested calendar could not be read
     */
    502: {
        data: null;
        error: string;
    };
};

export type GetV1UsersByUserIdSchedulingError = GetV1UsersByUserIdSchedulingErrors[keyof GetV1UsersByUserIdSchedulingErrors];

export type GetV1UsersByUserIdSchedulingResponses = {
    /**
     * Available time slots
     */
    200: {
        data: {
            availableSlots: Array<TimeRange>;
            options: {
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                maxOverlaps: number;
                /**
                 * Padding in minutes to add before and after busy times
                 */
                padding: number;
                /**
                 * Duration of each slot in minutes
                 */
                slotDuration: number;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                /**
                 * Requested earliest time of each day (in the time zone of the request)
                 */
                earliestTimeEachDay?: string;
                /**
                 * Requested latest time of each day (in the time zone of the request)
                 */
                latestTimeEachDay?: string;
            };
        };
    };
};

export type GetV1UsersByUserIdSchedulingResponse = GetV1UsersByUserIdSchedulingResponses[keyof GetV1UsersByUserIdSchedulingResponses];

export type PostV1UsersByUserIdSchedulingData = {
    body: {
        schedules: Array<{
            /**
             * The days to apply this scheduling element to
             */
            days: Array<'friday' | 'monday' | 'saturday' | 'sunday' | 'thursday' | 'tuesday' | 'wednesday'>;
            /**
             * End time
             */
            end: string;
            /**
             * Start time
             */
            start: string;
        }>;
    };
    path: {
        userId: string;
    };
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        /**
         * an integer >= 0 (default: 0)
         */
        maxOverlaps?: string;
        /**
         * Padding in minutes to add before and after busy times
         */
        padding?: string;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
        /**
         * Duration of each slot in minutes
         */
        slotDuration?: string;
    };
    url: '/v1/users/{userId}/scheduling';
};

export type PostV1UsersByUserIdSchedulingErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        data: null;
    };
    /**
     * Calendar provider rejected the stored access token
     */
    401: {
        data: null;
        error: string;
    };
    /**
     * Every requested calendar was denied by the provider, has no mailbox behind it, or the authorization does not cover busy times
     */
    403: {
        data: null;
        error: string;
    };
    /**
     * User not found, or the user has no connected calendars
     */
    404: {
        data: null;
        error: string;
    };
    /**
     * The calendar provider throttled every requested calendar
     */
    429: {
        data: null;
        error: string;
    };
    /**
     * Every requested calendar could not be read
     */
    502: {
        data: null;
        error: string;
    };
};

export type PostV1UsersByUserIdSchedulingError = PostV1UsersByUserIdSchedulingErrors[keyof PostV1UsersByUserIdSchedulingErrors];

export type PostV1UsersByUserIdSchedulingResponses = {
    /**
     * Available time slots
     */
    200: {
        data: {
            availableSlots: Array<TimeRange>;
            options: {
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                maxOverlaps: number;
                /**
                 * Padding in minutes to add before and after busy times
                 */
                padding: number;
                /**
                 * Duration of each slot in minutes
                 */
                slotDuration: number;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                /**
                 * Requested earliest time of each day (in the time zone of the request)
                 */
                earliestTimeEachDay?: string;
                /**
                 * Requested latest time of each day (in the time zone of the request)
                 */
                latestTimeEachDay?: string;
            };
        };
    };
};

export type PostV1UsersByUserIdSchedulingResponse = PostV1UsersByUserIdSchedulingResponses[keyof PostV1UsersByUserIdSchedulingResponses];

export type PostV1UsersSchedulingData = {
    body: {
        users: Array<{
            id: string;
            calendarIds?: string | Array<string>;
            schedules?: {
                /**
                 * The days to apply this scheduling element to
                 */
                days: Array<'friday' | 'monday' | 'saturday' | 'sunday' | 'thursday' | 'tuesday' | 'wednesday'>;
                /**
                 * End time
                 */
                end: string;
                /**
                 * Start time
                 */
                start: string;
            } | Array<{
                /**
                 * The days to apply this scheduling element to
                 */
                days: Array<'friday' | 'monday' | 'saturday' | 'sunday' | 'thursday' | 'tuesday' | 'wednesday'>;
                /**
                 * End time
                 */
                end: string;
                /**
                 * Start time
                 */
                start: string;
            }>;
        }>;
    };
    path?: never;
    query: {
        /**
         * End time of the time range in ISO format
         */
        end: string;
        /**
         * Start time of the time range in ISO format
         */
        start: string;
        /**
         * an integer >= 0 (default: 0)
         */
        maxOverlaps?: string;
        /**
         * Padding in minutes to add before and after busy times
         */
        padding?: string;
        provider?: Array<'google' | 'microsoft'> | 'google' | 'microsoft';
        /**
         * Duration of each slot in minutes
         */
        slotDuration?: string;
    };
    url: '/v1/users/scheduling';
};

export type PostV1UsersSchedulingErrors = {
    /**
     * Validation Error
     */
    400: {
        error: string;
        data: null;
    };
};

export type PostV1UsersSchedulingError = PostV1UsersSchedulingErrors[keyof PostV1UsersSchedulingErrors];

export type PostV1UsersSchedulingResponses = {
    /**
     * Available time slots for each user, plus the calendars that could not be read
     */
    200: {
        data: Array<{
            availableSlots: Array<TimeRange>;
            failedCalendars: Array<FailedCalendar>;
            options: {
                /**
                 * End time of the time range in ISO format
                 */
                end: Date;
                maxOverlaps: number;
                /**
                 * Padding in minutes to add before and after busy times
                 */
                padding: number;
                /**
                 * Duration of each slot in minutes
                 */
                slotDuration: number;
                /**
                 * Start time of the time range in ISO format
                 */
                start: Date;
                /**
                 * Requested earliest time of each day (in the time zone of the request)
                 */
                earliestTimeEachDay?: string;
                /**
                 * Requested latest time of each day (in the time zone of the request)
                 */
                latestTimeEachDay?: string;
            };
            status: 'ok';
            userId: string;
            calendarIds?: string | Array<string>;
            schedules?: {
                /**
                 * The days to apply this scheduling element to
                 */
                days: Array<'friday' | 'monday' | 'saturday' | 'sunday' | 'thursday' | 'tuesday' | 'wednesday'>;
                /**
                 * End time
                 */
                end: string;
                /**
                 * Start time
                 */
                start: string;
            } | Array<{
                /**
                 * The days to apply this scheduling element to
                 */
                days: Array<'friday' | 'monday' | 'saturday' | 'sunday' | 'thursday' | 'tuesday' | 'wednesday'>;
                /**
                 * End time
                 */
                end: string;
                /**
                 * Start time
                 */
                start: string;
            }>;
        } | {
            error: string;
            status: 'error';
            userId: string;
            reason?: FreeBusyFailureReason;
        }>;
    };
};

export type PostV1UsersSchedulingResponse = PostV1UsersSchedulingResponses[keyof PostV1UsersSchedulingResponses];
