// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * User
 */
export const zUser = z.object({
    createdAt: z.iso.datetime({
        offset: true
    }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
    id: z.string()
});

/**
 * Organization
 */
export const zOrganization = z.object({
    createdAt: z.iso.datetime({
        offset: true
    }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
    name: z.union([
        z.string().min(3).max(128),
        z.null()
    ]),
    slug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/),
    members: z.optional(z.array(zUser))
});

/**
 * OAuth Connection
 */
export const zAuthConnection = z.object({
    alive: z.boolean(),
    email: z.union([
        z.email().regex(/^[\w%+.-]+@[\d.A-Za-z-]+\.[A-Za-z]{2,}$/),
        z.null()
    ]),
    expiresAt: z.union([
        z.iso.datetime({
            offset: true
        }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        z.null()
    ]),
    provider: z.enum([
        'google',
        'microsoft'
    ]),
    scope: z.array(z.string()),
    accessToken: z.optional(z.unknown()),
    refreshToken: z.optional(z.unknown())
});

/**
 * Recal Normalized Time Range
 */
export const zTimeRange = z.object({
    end: z.iso.datetime({
        offset: true
    }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
    start: z.iso.datetime({
        offset: true
    }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)
});

/**
 * Recal Normalized Calendar
 */
export const zCalendar = z.object({
    id: z.string(),
    original: z.unknown(),
    provider: z.enum([
        'google',
        'microsoft'
    ]),
    accessRole: z.optional(z.enum([
        'freeBusyReader',
        'owner',
        'reader',
        'writer'
    ])),
    backgroundColor: z.optional(z.string()),
    foregroundColor: z.optional(z.string()),
    selected: z.optional(z.boolean()),
    subject: z.optional(z.string()),
    timeZone: z.optional(z.string().regex(/^([A-Za-z_]+(?:\/[A-Za-z_]+){1,2}|UTC)$/))
});

/**
 * Recal Normalized Event
 */
export const zEvent = z.object({
    attendees: z.array(z.union([
        z.object({
            email: z.string(),
            responseStatus: z.union([
                z.literal('accepted'),
                z.literal('declined'),
                z.literal('needsAction'),
                z.literal('tentative'),
                z.unknown()
            ])
        }),
        z.object({
            email: z.string(),
            self: z.literal(true)
        })
    ])),
    calendarId: z.string(),
    id: z.string(),
    original: z.unknown(),
    description: z.optional(z.string()),
    end: z.optional(z.iso.datetime({
        offset: true
    }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)),
    location: z.optional(z.string()),
    metaId: z.optional(z.string()),
    start: z.optional(z.iso.datetime({
        offset: true
    }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)),
    subject: z.optional(z.string())
});

/**
 * Recal Normalized Create Event
 */
export const zCreateEventAcrossCalendars = z.object({
    attendees: z.optional(z.array(z.object({
        email: z.email().regex(/^[\w%+.-]+@[\d.A-Za-z-]+\.[A-Za-z]{2,}$/)
    }))),
    description: z.optional(z.string()),
    end: z.optional(z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)),
    location: z.optional(z.string()),
    meeting: z.optional(z.union([
        z.object({
            url: z.url()
        }),
        z.boolean()
    ])),
    metaId: z.optional(z.string()),
    sendNotificationsFor: z.optional(z.array(z.enum([
        'google',
        'microsoft'
    ]))),
    start: z.optional(z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)),
    subject: z.optional(z.string())
});

/**
 * Recal Normalized Update Event
 */
export const zUpdateEvent = z.object({
    attendees: z.optional(z.array(z.object({
        email: z.email().regex(/^[\w%+.-]+@[\d.A-Za-z-]+\.[A-Za-z]{2,}$/)
    }))),
    description: z.optional(z.string()),
    end: z.optional(z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)),
    id: z.optional(z.string()),
    location: z.optional(z.string()),
    meeting: z.optional(z.union([
        z.object({
            url: z.url()
        }),
        z.boolean()
    ])),
    metaId: z.optional(z.string()),
    sendNotifications: z.optional(z.boolean()),
    start: z.optional(z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)),
    subject: z.optional(z.string())
});

/**
 * Recal Normalized Create Event
 */
export const zCreateEvent = z.object({
    attendees: z.array(z.object({
        email: z.email().regex(/^[\w%+.-]+@[\d.A-Za-z-]+\.[A-Za-z]{2,}$/)
    })),
    description: z.optional(z.string()),
    end: z.optional(z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)),
    id: z.optional(z.string()),
    location: z.optional(z.string()),
    meeting: z.optional(z.union([
        z.object({
            url: z.url()
        }),
        z.boolean()
    ])),
    metaId: z.optional(z.string()),
    sendNotifications: z.optional(z.boolean()),
    start: z.optional(z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/)),
    subject: z.optional(z.string())
});

export const zGetV1OrganizationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * All organizations
 */
export const zGetV1OrganizationsResponse = z.object({
    data: z.array(zOrganization)
});

export const zPostV1OrganizationsData = z.object({
    body: z.optional(z.object({
        name: z.union([
            z.string().min(3).max(128),
            z.null()
        ]),
        slug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created organization
 */
export const zPostV1OrganizationsResponse = z.object({
    data: zOrganization
});

export const zDeleteV1OrganizationsOrgSlugData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        orgSlug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * Deleted organization
 */
export const zDeleteV1OrganizationsOrgSlugResponse = z.object({
    data: zOrganization
});

export const zGetV1OrganizationsOrgSlugData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        orgSlug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * Organization
 */
export const zGetV1OrganizationsOrgSlugResponse = z.object({
    data: zOrganization
});

export const zPutV1OrganizationsOrgSlugData = z.object({
    body: z.optional(z.object({
        name: z.union([
            z.string().min(3).max(128),
            z.null()
        ]),
        slug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    })),
    path: z.object({
        orgSlug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * Updated organization
 */
export const zPutV1OrganizationsOrgSlugResponse = z.object({
    data: zOrganization
});

export const zDeleteV1OrganizationsOrgSlugMembersData = z.object({
    body: z.optional(z.object({
        userIds: z.array(z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/))
    })),
    path: z.object({
        orgSlug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

export const zDeleteV1OrganizationsOrgSlugMembersResponse = z.object({
    data: z.string()
});

export const zGetV1OrganizationsOrgSlugMembersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        orgSlug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        include: z.optional(z.union([
            z.array(z.enum([
                'oauthConnections',
                'organizations'
            ])),
            z.literal('oauthConnections'),
            z.literal('organizations')
        ]))
    }))
});

/**
 * All members of an organization
 */
export const zGetV1OrganizationsOrgSlugMembersResponse = z.object({
    data: z.array(z.object({
        createdAt: z.iso.datetime({
            offset: true
        }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        id: z.string(),
        oauthConnections: z.optional(z.array(zAuthConnection)),
        organizations: z.optional(z.array(zOrganization))
    }))
});

export const zPostV1OrganizationsOrgSlugMembersData = z.object({
    body: z.optional(z.object({
        userIds: z.array(z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/))
    })),
    path: z.object({
        orgSlug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

export const zPostV1OrganizationsOrgSlugMembersResponse = z.union([
    z.object({
        data: z.string()
    }),
    z.object({
        data: z.string()
    })
]);

export const zGetV1OrganizationsOrgSlugCalendarBusyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        orgSlug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.object({
        end: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        start: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        primaryOnly: z.optional(z.union([
            z.literal('false'),
            z.literal('true')
        ])),
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    })
});

/**
 * Busy times of all users of an organization
 */
export const zGetV1OrganizationsOrgSlugCalendarBusyResponse = z.object({
    data: z.array(zTimeRange)
});

export const zGetV1OrganizationsOrgSlugSchedulingData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        orgSlug: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.object({
        end: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        padding: z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]),
        slotDuration: z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]),
        start: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        earliestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)),
        latestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)),
        maxOverlaps: z.optional(z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ])),
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    })
});

/**
 * Available time slots
 */
export const zGetV1OrganizationsOrgSlugSchedulingResponse = z.object({
    data: z.object({
        availableSlots: z.array(z.object({
            end: z.iso.datetime({
                offset: true
            }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            start: z.iso.datetime({
                offset: true
            }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
        })),
        options: z.object({
            end: z.iso.datetime({
                offset: true
            }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            maxOverlaps: z.int(),
            padding: z.int(),
            slotDuration: z.int(),
            start: z.iso.datetime({
                offset: true
            }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            earliestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)),
            latestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/))
        })
    })
});

export const zGetV1UsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * List of users
 */
export const zGetV1UsersResponse = z.object({
    data: z.array(z.object({
        createdAt: z.iso.datetime({
            offset: true
        }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        id: z.string(),
        oauthConnections: z.optional(z.array(zAuthConnection)),
        organizations: z.optional(z.array(zOrganization))
    }))
});

export const zPostV1UsersData = z.object({
    body: z.optional(z.object({
        id: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/),
        organizationSlugs: z.optional(z.array(z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)))
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created user
 */
export const zPostV1UsersResponse = z.object({
    data: z.object({
        createdAt: z.iso.datetime({
            offset: true
        }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        id: z.string(),
        oauthConnections: z.optional(z.array(zAuthConnection)),
        organizations: z.optional(z.array(zOrganization))
    })
});

export const zDeleteV1UsersUserIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * User
 */
export const zDeleteV1UsersUserIdResponse = z.object({
    data: z.object({
        createdAt: z.iso.datetime({
            offset: true
        }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        id: z.string(),
        oauthConnections: z.optional(z.array(zAuthConnection)),
        organizations: z.optional(z.array(zOrganization))
    })
});

export const zGetV1UsersUserIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        include: z.optional(z.union([
            z.array(z.enum([
                'oauthConnections',
                'organizations'
            ])),
            z.literal('oauthConnections'),
            z.literal('organizations')
        ]))
    }))
});

/**
 * User
 */
export const zGetV1UsersUserIdResponse = z.object({
    data: z.object({
        createdAt: z.iso.datetime({
            offset: true
        }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        id: z.string(),
        oauthConnections: z.optional(z.array(zAuthConnection)),
        organizations: z.optional(z.array(zOrganization))
    })
});

export const zPutV1UsersUserIdData = z.object({
    body: z.optional(z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    })),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * User
 */
export const zPutV1UsersUserIdResponse = z.object({
    data: z.object({
        createdAt: z.iso.datetime({
            offset: true
        }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        id: z.string(),
        oauthConnections: z.optional(z.array(zAuthConnection)),
        organizations: z.optional(z.array(zOrganization))
    })
});

export const zGetV1UsersUserIdOrganizationsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * List of organizations
 */
export const zGetV1UsersUserIdOrganizationsResponse = z.object({
    data: z.array(zOrganization)
});

export const zGetV1UsersUserIdCalendarData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    }))
});

/**
 * List of calendars
 */
export const zGetV1UsersUserIdCalendarResponse = z.object({
    data: z.array(zCalendar)
});

export const zGetV1UsersUserIdCalendarBusyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.object({
        end: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        start: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        calendarIds: z.optional(z.array(z.string())),
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    })
});

/**
 * List of busy intervals
 */
export const zGetV1UsersUserIdCalendarBusyResponse = z.object({
    data: z.array(zTimeRange)
});

export const zGetV1UsersUserIdCalendarEventsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.object({
        end: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        start: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        calendarIds: z.optional(z.array(z.string())),
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    })
});

/**
 * List of events
 */
export const zGetV1UsersUserIdCalendarEventsResponse = z.object({
    data: z.array(zEvent)
});

export const zPostV1UsersUserIdCalendarEventsMetaData = z.object({
    body: z.optional(zCreateEventAcrossCalendars),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    }))
});

/**
 * Event created
 */
export const zPostV1UsersUserIdCalendarEventsMetaResponse = z.object({
    data: zEvent
});

export const zDeleteV1UsersUserIdCalendarEventsMetaMetaIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        metaId: z.string(),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    }))
});

/**
 * Event deleted
 */
export const zDeleteV1UsersUserIdCalendarEventsMetaMetaIdResponse = z.object({
    data: zEvent
});

export const zGetV1UsersUserIdCalendarEventsMetaMetaIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        metaId: z.string(),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    }))
});

/**
 * Event
 */
export const zGetV1UsersUserIdCalendarEventsMetaMetaIdResponse = z.object({
    data: zEvent
});

export const zPutV1UsersUserIdCalendarEventsMetaMetaIdData = z.object({
    body: z.optional(zUpdateEvent),
    path: z.object({
        metaId: z.string(),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    }))
});

/**
 * Event updated
 */
export const zPutV1UsersUserIdCalendarEventsMetaMetaIdResponse = z.object({
    data: zEvent
});

export const zPostV1UsersUserIdCalendarEventsProviderCalendarIdData = z.object({
    body: z.optional(zCreateEvent),
    path: z.object({
        calendarId: z.string(),
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * Event created
 */
export const zPostV1UsersUserIdCalendarEventsProviderCalendarIdResponse = z.object({
    data: zEvent
});

export const zDeleteV1UsersUserIdCalendarEventsProviderCalendarIdEventIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        calendarId: z.string(),
        eventId: z.string(),
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * Event deleted
 */
export const zDeleteV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse = z.object({
    data: zEvent
});

export const zGetV1UsersUserIdCalendarEventsProviderCalendarIdEventIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        calendarId: z.string(),
        eventId: z.string(),
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * Event found
 */
export const zGetV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse = z.object({
    data: zEvent
});

export const zPutV1UsersUserIdCalendarEventsProviderCalendarIdEventIdData = z.object({
    body: z.optional(zUpdateEvent),
    path: z.object({
        calendarId: z.string(),
        eventId: z.string(),
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * Event updated
 */
export const zPutV1UsersUserIdCalendarEventsProviderCalendarIdEventIdResponse = z.object({
    data: zEvent
});

export const zGetV1UsersUserIdOauthData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        showToken: z.optional(z.union([
            z.literal('false'),
            z.literal('true')
        ]))
    }))
});

/**
 * All oauth connections of the user
 */
export const zGetV1UsersUserIdOauthResponse = z.object({
    data: z.array(zAuthConnection)
});

export const zDeleteV1UsersUserIdOauthProviderData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

export const zGetV1UsersUserIdOauthProviderData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.object({
        showToken: z.optional(z.union([
            z.literal('false'),
            z.literal('true')
        ]))
    }))
});

/**
 * OAuth connection of the user
 */
export const zGetV1UsersUserIdOauthProviderResponse = z.object({
    data: zAuthConnection
});

export const zPostV1UsersUserIdOauthProviderData = z.object({
    body: z.optional(z.object({
        accessToken: z.string(),
        email: z.union([
            z.email().regex(/^[\w%+.-]+@[\d.A-Za-z-]+\.[A-Za-z]{2,}$/),
            z.null()
        ]),
        expiresAt: z.union([
            z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            z.null()
        ]),
        refreshToken: z.union([
            z.string(),
            z.unknown()
        ]),
        scope: z.array(z.string())
    })),
    path: z.object({
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * OAuth connection created
 */
export const zPostV1UsersUserIdOauthProviderResponse = z.object({
    data: zAuthConnection
});

export const zGetV1UsersUserIdOauthLinksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.object({
        accessType: z.union([
            z.literal('offline'),
            z.literal('online')
        ]),
        scope: z.union([
            z.array(z.string()),
            z.literal('edit'),
            z.literal('free-busy')
        ]),
        provider: z.optional(z.array(z.enum([
            'google',
            'microsoft'
        ])))
    })
});

/**
 * Auth urls for the oauth providers
 */
export const zGetV1UsersUserIdOauthLinksResponse = z.object({
    data: zAuthConnection
});

export const zGetV1UsersUserIdOauthProviderLinkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.object({
        accessType: z.union([
            z.literal('offline'),
            z.literal('online')
        ]),
        scope: z.union([
            z.array(z.string()),
            z.literal('edit'),
            z.literal('free-busy')
        ]),
        redirectUrl: z.optional(z.url())
    })
});

/**
 * Auth url for the oauth provider
 */
export const zGetV1UsersUserIdOauthProviderLinkResponse = z.object({
    data: z.url()
});

export const zPostV1UsersOauthProviderVerifyData = z.object({
    body: z.optional(z.object({
        code: z.string(),
        scope: z.array(z.string()),
        state: z.string()
    })),
    path: z.object({
        provider: z.enum([
            'google',
            'microsoft'
        ])
    }),
    query: z.optional(z.object({
        redirectUrl: z.optional(z.url())
    }))
});

export const zGetV1UsersUserIdOauthProviderTokenData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        provider: z.enum([
            'google',
            'microsoft'
        ]),
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.optional(z.never())
});

/**
 * Access token
 */
export const zGetV1UsersUserIdOauthProviderTokenResponse = z.object({
    data: z.object({
        accessToken: z.string()
    })
});

export const zGetV1UsersUserIdSchedulingData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.object({
        end: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        padding: z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]),
        provider: z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]),
        slotDuration: z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]),
        start: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        earliestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)),
        latestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)),
        maxOverlaps: z.optional(z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]))
    })
});

/**
 * Available time slots
 */
export const zGetV1UsersUserIdSchedulingResponse = z.object({
    data: z.object({
        availableSlots: z.array(zTimeRange),
        options: z.object({
            end: z.iso.datetime({
                offset: true
            }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            maxOverlaps: z.int(),
            padding: z.int(),
            slotDuration: z.int(),
            start: z.iso.datetime({
                offset: true
            }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            earliestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)),
            latestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/))
        })
    })
});

export const zPostV1UsersUserIdSchedulingData = z.object({
    body: z.optional(z.object({
        schedules: z.array(z.object({
            days: z.array(z.enum([
                'friday',
                'monday',
                'saturday',
                'sunday',
                'thursday',
                'tuesday',
                'wednesday'
            ])),
            end: z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
            start: z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)
        }))
    })),
    path: z.object({
        userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
    }),
    query: z.object({
        end: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        padding: z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]),
        slotDuration: z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]),
        start: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        maxOverlaps: z.optional(z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ])),
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    })
});

/**
 * Available time slots
 */
export const zPostV1UsersUserIdSchedulingResponse = z.object({
    data: z.object({
        availableSlots: z.array(zTimeRange),
        options: z.object({
            end: z.iso.datetime({
                offset: true
            }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            maxOverlaps: z.int(),
            padding: z.int(),
            slotDuration: z.int(),
            start: z.iso.datetime({
                offset: true
            }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
            earliestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)),
            latestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/))
        })
    })
});

export const zPostV1UsersSchedulingData = z.object({
    body: z.optional(z.object({
        users: z.array(z.object({
            id: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/),
            calendarIds: z.optional(z.array(z.string())),
            schedules: z.optional(z.array(z.object({
                days: z.array(z.enum([
                    'friday',
                    'monday',
                    'saturday',
                    'sunday',
                    'thursday',
                    'tuesday',
                    'wednesday'
                ])),
                end: z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
                start: z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)
            })))
        }))
    })),
    path: z.optional(z.never()),
    query: z.object({
        end: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        padding: z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]),
        slotDuration: z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ]),
        start: z.string().regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
        maxOverlaps: z.optional(z.union([
            z.string().regex(/^(?:(?!^-0$)-?(?:(?:0|[1-9]\d*)))$/),
            z.unknown()
        ])),
        provider: z.optional(z.union([
            z.array(z.enum([
                'google',
                'microsoft'
            ])),
            z.literal('google'),
            z.literal('microsoft')
        ]))
    })
});

/**
 * Available time slots for each user
 */
export const zPostV1UsersSchedulingResponse = z.object({
    data: z.union([
        z.object({
            error: z.string(),
            userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/)
        }),
        z.array(z.object({
            availableSlots: z.array(zTimeRange),
            options: z.object({
                end: z.iso.datetime({
                    offset: true
                }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
                maxOverlaps: z.int(),
                padding: z.int(),
                slotDuration: z.int(),
                start: z.iso.datetime({
                    offset: true
                }).regex(/^([+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-3])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))(T((([01]\d|2[0-3])((:?)[0-5]\d)?|24:?00)([,.]\d+(?!:))?)?(\17[0-5]\d([,.]\d+)?)?([Zz]|([+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/),
                earliestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)),
                latestTimeEachDay: z.optional(z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/))
            }),
            userId: z.string().regex(/^[a-z0-9][a-z0-9_-]{2,127}$/),
            calendarIds: z.optional(z.array(z.string())),
            schedules: z.optional(z.array(z.object({
                days: z.array(z.enum([
                    'friday',
                    'monday',
                    'saturday',
                    'sunday',
                    'thursday',
                    'tuesday',
                    'wednesday'
                ])),
                end: z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
                start: z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/)
            })))
        }))
    ])
});
